# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions.

#' List all serviceNames for a particular provider
#'
#' List all serviceNames in the directory for a particular providerName
#' 
#' @param provider (length-1 `character`) 
#' @inheritParams .shared-params
#'
#' @returns `get_services()`: The API response.
#' @export
get_services <- function(provider, max_reqs = Inf, max_tries_per_req = 3) {
  req <- req_get_services(provider = provider)
  resps <- nectar::req_perform_opinionated(
    req,
    max_reqs = max_reqs,
    max_tries_per_req = max_tries_per_req
  )
  return(nectar::resp_parse(resps))
}

#' @rdname get_services
#' @returns `req_get_services()`: (`httr2_request`) A [httr2::request()] object.
req_get_services <- function(provider) {
  provider <- stbl::to_chr_scalar(provider)
  guru_req_prepare(
    path = c("/{provider}/services.json", provider = provider),
    method = "get",
    tidy_policy = tidy_policy_get_services()
  )
}

tidy_policy_get_services <- function() {
  spec <- tibblify::tspec_row(
    tibblify::tib_chr_vec("data", .required = FALSE),
  )
  nectar::tidy_policy_json(spec = spec)
}
