# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions.

#' Retrieve one version of a particular API
#'
#' Returns the API entry for one specific version of an API where there is no serviceName.
#' 
#' @param provider (length-1 `character`) 
#' @param api (length-1 `character`) 
#' @inheritParams .shared-params
#'
#' @returns `get_api()`: The API response.
#' @export
get_api <- function(provider, api, max_reqs = Inf, max_tries_per_req = 3) {
  req <- req_get_api(provider = provider, api = api)
  resps <- nectar::req_perform_opinionated(
    req,
    max_reqs = max_reqs,
    max_tries_per_req = max_tries_per_req
  )
  return(nectar::resp_parse(resps))
}

#' @rdname get_api
#' @returns `req_get_api()`: (`httr2_request`) A [httr2::request()] object.
req_get_api <- function(provider, api) {
  provider <- stbl::to_chr_scalar(provider)
  api <- stbl::to_chr_scalar(api)
  guru_req_prepare(
    path = c("/specs/{provider}/{api}.json", provider = provider, api = api),
    method = "get",
    tidy_policy = tidy_policy_get_api()
  )
}

tidy_policy_get_api <- function() {
  spec <- tibblify::tspec_row(
  tibblify::tib_chr("added"),
  tibblify::tib_chr("preferred"),
  tibblify::tib_row(
    "versions",
    tibblify::tib_chr("added"),
    tibblify::tib_row(
      "externalDocs",
      .required = FALSE,
    ),
    tibblify::tib_row(
      "info",
    ),
    tibblify::tib_chr("link", .required = FALSE),
    tibblify::tib_chr("openapiVer"),
    tibblify::tib_chr("swaggerUrl"),
    tibblify::tib_chr("swaggerYamlUrl"),
    tibblify::tib_chr("updated"),
  ),
)
  nectar::tidy_policy_json(spec = spec)
}
