# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions.

#' List all APIs for a particular provider
#'
#' List all APIs in the directory for a particular providerName Returns links to the individual API entry for each API.
#' 
#' @param provider (length-1 `character`) 
#' @inheritParams .shared-params
#'
#' @returns `get_provider()`: The API response.
#' @export
get_provider <- function(provider, max_reqs = Inf, max_tries_per_req = 3) {
  req <- req_get_provider(provider = provider)
  resps <- nectar::req_perform_opinionated(
    req,
    max_reqs = max_reqs,
    max_tries_per_req = max_tries_per_req
  )
  return(nectar::resp_parse(resps))
}

#' @rdname get_provider
#' @returns `req_get_provider()`: (`httr2_request`) A [httr2::request()] object.
req_get_provider <- function(provider) {
  provider <- stbl::to_chr_scalar(provider)
  guru_req_prepare(
    path = c("/{provider}.json", provider = provider),
    method = "get"
  )
}
