# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions.

#' List all providers
#'
#' List all the providers in the directory
#' 
#' @inheritParams .shared-params
#'
#' @returns `get_providers()`: The API response.
#' @export
get_providers <- function(max_reqs = Inf, max_tries_per_req = 3) {
  req <- req_get_providers()
  resps <- nectar::req_perform_opinionated(
    req,
    max_reqs = max_reqs,
    max_tries_per_req = max_tries_per_req
  )
  return(nectar::resp_parse(resps))
}

#' @rdname get_providers
#' @returns `req_get_providers()`: (`httr2_request`) A [httr2::request()] object.
req_get_providers <- function() {
  guru_req_prepare(
    path = "/providers.json",
    method = "get",
    tidy_policy = tidy_policy_get_providers()
  )
}

tidy_policy_get_providers <- function() {
  spec <- tibblify::tspec_row(
  tibblify::tib_chr_vec("data", .required = FALSE),
)
  nectar::tidy_policy_json_tibblify(spec = spec)
}
