# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions.

#' Get schedules schedule d sub id
#'
#' Schedule D, it shows debts and obligations owed to or by the committee that are required to be disclosed.
#' 
#' @param sort_nulls_last (length-1 `logical`, optional) Toggle that sorts null values last
#' @param per_page (length-1 `list`, optional) The number of results returned per page. Defaults to 20.
#' @param sort_null_only (length-1 `logical`, optional) Toggle that filters out all rows having sort column that is non-null
#' @param sort_hide_null (length-1 `logical`, optional) Hide null values on sorted column(s).
#' @param sort (length-1 `character`, optional) Provide a field to sort by. Use `-` for descending order.
#' @param api_key (length-1 `character`) API key for https://api.data.gov. Get one at https://api.data.gov/signup.
#' @param page (length-1 `list`, optional) For paginating through results, starting at page 1
#' @param sub_id (length-1 `character`) 
#' @inheritParams .shared-params
#'
#' @returns `get_schedules_schedule_d_sub_id()`: The API response.
#' @export
get_schedules_schedule_d_sub_id <- function(sort_nulls_last, per_page, sort_null_only, sort_hide_null, sort, page, sub_id, api_key = Sys.getenv("FEC_API_KEY"), max_reqs = Inf, max_tries_per_req = 3) {
  req <- req_get_schedules_schedule_d_sub_id(sort_nulls_last = sort_nulls_last, per_page = per_page, sort_null_only = sort_null_only, sort_hide_null = sort_hide_null, sort = sort, page = page, sub_id = sub_id, api_key = api_key)
  resps <- nectar::req_perform_opinionated(
    req,
    max_reqs = max_reqs,
    max_tries_per_req = max_tries_per_req
  )
  return(nectar::resp_parse(resps))
}

#' @rdname get_schedules_schedule_d_sub_id
#' @returns `req_get_schedules_schedule_d_sub_id()`: (`httr2_request`) A [httr2::request()] object.
req_get_schedules_schedule_d_sub_id <- function(sort_nulls_last, per_page, sort_null_only, sort_hide_null, sort, page, sub_id, api_key = Sys.getenv("FEC_API_KEY")) {
  sort_nulls_last <- stbl::to_lgl_scalar(sort_nulls_last)
  sort_null_only <- stbl::to_lgl_scalar(sort_null_only)
  sort_hide_null <- stbl::to_lgl_scalar(sort_hide_null)
  sort <- stbl::to_chr_scalar(sort)
  sub_id <- stbl::to_chr_scalar(sub_id)
  fec_req_prepare(
    path = c("/schedules/schedule_d/{sub_id}/", sub_id = sub_id),
    method = "get",
    api_key = api_key,
    query = list(sort_nulls_last = sort_nulls_last, per_page = per_page, sort_null_only = sort_null_only, sort_hide_null = sort_hide_null, sort = sort, page = page),
    tidy_policy = tidy_policy_get_schedules_schedule_d_sub_id()
  )
}

tidy_policy_get_schedules_schedule_d_sub_id <- function() {
  spec <- tibblify::tspec_row(
    tibblify::tib_row(
      "pagination",
      .required = FALSE,
      tibblify::tib_int("count", .required = FALSE),
      tibblify::tib_int("page", .required = FALSE),
      tibblify::tib_int("pages", .required = FALSE),
      tibblify::tib_int("per_page", .required = FALSE),
    ),
    tibblify::tib_df(
      "results",
      .required = FALSE,
      tibblify::tib_chr("action_code", .required = FALSE),
      tibblify::tib_chr("action_code_full", .required = FALSE),
      tibblify::tib_dbl("amount_incurred_period", .required = FALSE),
      tibblify::tib_chr("candidate_first_name", .required = FALSE),
      tibblify::tib_chr("candidate_id", .required = FALSE),
      tibblify::tib_chr("candidate_last_name", .required = FALSE),
      tibblify::tib_chr("candidate_name", .required = FALSE),
      tibblify::tib_chr("candidate_office", .required = FALSE),
      tibblify::tib_chr("candidate_office_district", .required = FALSE),
      tibblify::tib_chr("candidate_office_state", .required = FALSE),
      tibblify::tib_chr("candidate_office_state_full", .required = FALSE),
      tibblify::tib_row(
        "committee",
        .required = FALSE,
        tibblify::tib_chr("affiliated_committee_name", .required = FALSE),
        tibblify::tib_chr_vec("candidate_ids", .required = FALSE),
        tibblify::tib_chr("city", .required = FALSE),
        tibblify::tib_chr("committee_id"),
        tibblify::tib_chr("committee_type", .required = FALSE),
        tibblify::tib_chr("committee_type_full", .required = FALSE),
        tibblify::tib_int("cycle"),
        tibblify::tib_int_vec("cycles", .required = FALSE),
        tibblify::tib_int_vec("cycles_has_activity", .required = FALSE),
        tibblify::tib_int_vec("cycles_has_financial", .required = FALSE),
        tibblify::tib_chr("designation", .required = FALSE),
        tibblify::tib_chr("designation_full", .required = FALSE),
        tibblify::tib_chr("filing_frequency", .required = FALSE),
        tibblify::tib_chr("first_f1_date", .required = FALSE),
        tibblify::tib_chr("first_file_date", .required = FALSE),
        tibblify::tib_lgl("is_active", .required = FALSE),
        tibblify::tib_df(
          "jfc_committee",
          .required = FALSE,
          tibblify::tib_chr("joint_committee_id", .required = FALSE),
          tibblify::tib_chr("joint_committee_name", .required = FALSE),
        ),
        tibblify::tib_int("last_cycle_has_activity", .required = FALSE),
        tibblify::tib_int("last_cycle_has_financial", .required = FALSE),
        tibblify::tib_chr("last_f1_date", .required = FALSE),
        tibblify::tib_chr("last_file_date", .required = FALSE),
        tibblify::tib_chr("name", .required = FALSE),
        tibblify::tib_chr("organization_type", .required = FALSE),
        tibblify::tib_chr("organization_type_full", .required = FALSE),
        tibblify::tib_chr("party", .required = FALSE),
        tibblify::tib_chr("party_full", .required = FALSE),
        tibblify::tib_chr("state", .required = FALSE),
        tibblify::tib_chr("state_full", .required = FALSE),
        tibblify::tib_chr("street_1", .required = FALSE),
        tibblify::tib_chr("street_2", .required = FALSE),
        tibblify::tib_chr("treasurer_name", .required = FALSE),
        tibblify::tib_chr("zip", .required = FALSE),
      ),
      tibblify::tib_chr("committee_id", .required = FALSE),
      tibblify::tib_chr("committee_name", .required = FALSE),
      tibblify::tib_chr("conduit_committee_city", .required = FALSE),
      tibblify::tib_chr("conduit_committee_id", .required = FALSE),
      tibblify::tib_chr("conduit_committee_name", .required = FALSE),
      tibblify::tib_chr("conduit_committee_state", .required = FALSE),
      tibblify::tib_chr("conduit_committee_street1", .required = FALSE),
      tibblify::tib_chr("conduit_committee_street2", .required = FALSE),
      tibblify::tib_int("conduit_committee_zip", .required = FALSE),
      tibblify::tib_chr("creditor_debtor_city", .required = FALSE),
      tibblify::tib_chr("creditor_debtor_first_name", .required = FALSE),
      tibblify::tib_chr("creditor_debtor_id", .required = FALSE),
      tibblify::tib_chr("creditor_debtor_last_name", .required = FALSE),
      tibblify::tib_chr("creditor_debtor_middle_name", .required = FALSE),
      tibblify::tib_chr("creditor_debtor_name", .required = FALSE),
      tibblify::tib_chr("creditor_debtor_prefix", .required = FALSE),
      tibblify::tib_chr("creditor_debtor_state", .required = FALSE),
      tibblify::tib_chr("creditor_debtor_street1", .required = FALSE),
      tibblify::tib_chr("creditor_debtor_street2", .required = FALSE),
      tibblify::tib_chr("creditor_debtor_suffix", .required = FALSE),
      tibblify::tib_int("election_cycle", .required = FALSE),
      tibblify::tib_chr("entity_type", .required = FALSE),
      tibblify::tib_int("file_number", .required = FALSE),
      tibblify::tib_chr("filing_form", .required = FALSE),
      tibblify::tib_chr("image_number", .required = FALSE),
      tibblify::tib_chr("line_number", .required = FALSE),
      tibblify::tib_int("link_id", .required = FALSE),
      tibblify::tib_chr("load_date", .required = FALSE),
      tibblify::tib_chr("nature_of_debt", .required = FALSE),
      tibblify::tib_int("original_sub_id", .required = FALSE),
      tibblify::tib_dbl(
        "outstanding_balance_beginning_of_period",
        .required = FALSE,
      ),
      tibblify::tib_dbl("outstanding_balance_close_of_period", .required = FALSE),
      tibblify::tib_dbl("payment_period", .required = FALSE),
      tibblify::tib_chr("pdf_url", .required = FALSE),
      tibblify::tib_chr("report_type", .required = FALSE),
      tibblify::tib_int("report_year", .required = FALSE),
      tibblify::tib_chr("schedule_type", .required = FALSE),
      tibblify::tib_chr("schedule_type_full", .required = FALSE),
      tibblify::tib_chr("sub_id", .required = FALSE),
      tibblify::tib_chr("transaction_id", .required = FALSE),
    ),
  )
  nectar::tidy_policy_json(spec = spec)
}
