# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions.

#' Get audit case
#'
#' This endpoint contains Final Audit Reports approved by the Commission since inception. The search can be based on information about the audited committee (Name, FEC ID Number, Type, Election Cycle) or the issues covered in the report.
#' 
#' @param audit_case_id (length-1 `list`, optional) Primary/foreign key for audit tables
#' @param cycle (length-1 `list`, optional) Filter records to only those that are applicable to a given two-year period. This cycle follows the traditional House election cycle and subdivides the presidential and Senate elections into comparable two-year blocks. The cycle begins with an odd year and is named for its ending, even year.
#' @param sub_category_id (length-1 `character`, optional) The finding id of an audit. Finding are a category of broader issues. Each category has an unique ID.
#' @param sort_nulls_last (length-1 `logical`, optional) Toggle that sorts null values last
#' @param sort_hide_null (length-1 `logical`, optional) Hide null values on sorted column(s).
#' @param min_election_cycle (length-1 `list`, optional) Filter records to only those that are applicable to a given two-year period. This cycle follows the traditional House election cycle and subdivides the presidential and Senate elections into comparable two-year blocks. The cycle begins with an odd year and is named for its ending, even year.
#' @param audit_id (length-1 `list`, optional) The audit issue. Each subcategory has an unique ID
#' @param q (length-1 `list`, optional) The name of the committee. If a committee changes its name, the most recent name will be shown. Committee names are not unique. Use committee_id for looking up records.
#' @param per_page (length-1 `list`, optional) The number of results returned per page. Defaults to 20.
#' @param max_election_cycle (length-1 `list`, optional) Filter records to only those that are applicable to a given two-year period. This cycle follows the traditional House election cycle and subdivides the presidential and Senate elections into comparable two-year blocks. The cycle begins with an odd year and is named for its ending, even year.
#' @param candidate_id (length-1 `list`, optional) A unique identifier assigned to each candidate registered with the FEC. If a person runs for several offices, that person will have separate candidate IDs for each office.
#' @param committee_type (length-1 `list`, optional) The one-letter type code of the organization: - C communication cost - D delegate - E electioneering communication - H House - I independent expenditure filer (not a committee) - N PAC - nonqualified - O independent expenditure-only (super PACs) - P presidential - Q PAC - qualified - S Senate - U single candidate independent expenditure - V PAC with non-contribution account, nonqualified - W PAC with non-contribution account, qualified - X party, nonqualified - Y party, qualified - Z national party non-federal account
#' @param qq (length-1 `list`, optional) Name of candidate running for office
#' @param page (length-1 `list`, optional) For paginating through results, starting at page 1
#' @param committee_id (length-1 `list`, optional) A unique identifier assigned to each committee or filer registered with the FEC. In general committee id's begin with the letter C which is followed by eight digits.
#' @param api_key (length-1 `character`) API key for https://api.data.gov. Get one at https://api.data.gov/signup.
#' @param committee_designation (length-1 `character`, optional) Type of committee: - H or S - Congressional - P - Presidential - X or Y or Z - Party - N or Q - PAC - I - Independent expenditure - O - Super PAC
#' @param primary_category_id (length-1 `character`, optional) Audit category ID (table PK)
#' @param sort_null_only (length-1 `logical`, optional) Toggle that filters out all rows having sort column that is non-null
#' @param sort (length-1 `list`, optional) Provide a field to sort by. Use `-` for descending order. ex: `-case_no`
#' @inheritParams .shared-params
#'
#' @returns `get_audit_case()`: The API response.
#' @export
get_audit_case <- function(audit_case_id, cycle, sub_category_id, sort_nulls_last, sort_hide_null, min_election_cycle, audit_id, q, per_page, max_election_cycle, candidate_id, committee_type, qq, page, committee_id, committee_designation, primary_category_id, sort_null_only, sort, api_key = Sys.getenv("FEC_API_KEY"), max_reqs = Inf, max_tries_per_req = 3) {
  req <- req_get_audit_case(audit_case_id = audit_case_id, cycle = cycle, sub_category_id = sub_category_id, sort_nulls_last = sort_nulls_last, sort_hide_null = sort_hide_null, min_election_cycle = min_election_cycle, audit_id = audit_id, q = q, per_page = per_page, max_election_cycle = max_election_cycle, candidate_id = candidate_id, committee_type = committee_type, qq = qq, page = page, committee_id = committee_id, committee_designation = committee_designation, primary_category_id = primary_category_id, sort_null_only = sort_null_only, sort = sort, api_key = api_key)
  resps <- nectar::req_perform_opinionated(
    req,
    max_reqs = max_reqs,
    max_tries_per_req = max_tries_per_req
  )
  return(nectar::resp_parse(resps))
}

#' @rdname get_audit_case
#' @returns `req_get_audit_case()`: (`httr2_request`) A [httr2::request()] object.
req_get_audit_case <- function(audit_case_id, cycle, sub_category_id, sort_nulls_last, sort_hide_null, min_election_cycle, audit_id, q, per_page, max_election_cycle, candidate_id, committee_type, qq, page, committee_id, committee_designation, primary_category_id, sort_null_only, sort, api_key = Sys.getenv("FEC_API_KEY")) {
  sub_category_id <- stbl::to_chr_scalar(sub_category_id)
  sort_nulls_last <- stbl::to_lgl_scalar(sort_nulls_last)
  sort_hide_null <- stbl::to_lgl_scalar(sort_hide_null)
  committee_designation <- stbl::to_chr_scalar(committee_designation)
  primary_category_id <- stbl::to_chr_scalar(primary_category_id)
  sort_null_only <- stbl::to_lgl_scalar(sort_null_only)
  fec_req_prepare(
    path = "/audit-case/",
    method = "get",
    api_key = api_key,
    query = list(audit_case_id = audit_case_id, cycle = cycle, sub_category_id = sub_category_id, sort_nulls_last = sort_nulls_last, sort_hide_null = sort_hide_null, min_election_cycle = min_election_cycle, audit_id = audit_id, q = q, per_page = per_page, max_election_cycle = max_election_cycle, candidate_id = candidate_id, committee_type = committee_type, qq = qq, page = page, committee_id = committee_id, committee_designation = committee_designation, primary_category_id = primary_category_id, sort_null_only = sort_null_only, sort = sort),
    tidy_policy = tidy_policy_get_audit_case()
  )
}

tidy_policy_get_audit_case <- function() {
  spec <- tibblify::tspec_row(
    tibblify::tib_row(
      "pagination",
      .required = FALSE,
      tibblify::tib_int("count", .required = FALSE),
      tibblify::tib_int("page", .required = FALSE),
      tibblify::tib_int("pages", .required = FALSE),
      tibblify::tib_int("per_page", .required = FALSE),
    ),
    tibblify::tib_df(
      "results",
      .required = FALSE,
      tibblify::tib_chr("audit_case_id", .required = FALSE),
      tibblify::tib_int("audit_id", .required = FALSE),
      tibblify::tib_chr("candidate_id", .required = FALSE),
      tibblify::tib_chr("candidate_name", .required = FALSE),
      tibblify::tib_chr("committee_description", .required = FALSE),
      tibblify::tib_chr("committee_designation", .required = FALSE),
      tibblify::tib_chr("committee_id", .required = FALSE),
      tibblify::tib_chr("committee_name", .required = FALSE),
      tibblify::tib_chr("committee_type", .required = FALSE),
      tibblify::tib_int("cycle", .required = FALSE),
      tibblify::tib_chr("far_release_date", .required = FALSE),
      tibblify::tib_chr("link_to_report", .required = FALSE),
      tibblify::tib_df(
        "primary_category_list",
        .required = FALSE,
        tibblify::tib_chr("primary_category_id", .required = FALSE),
        tibblify::tib_chr("primary_category_name", .required = FALSE),
        tibblify::tib_df(
          "sub_category_list",
          .required = FALSE,
          tibblify::tib_chr("sub_category_id", .required = FALSE),
          tibblify::tib_chr("sub_category_name", .required = FALSE),
        ),
      ),
    ),
  )
  nectar::tidy_policy_json(spec = spec)
}
