# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions.

#' Get schedules schedule d
#'
#' Schedule D, it shows debts and obligations owed to or by the committee that are required to be disclosed.
#' 
#' @param creditor_debtor_name (length-1 `list`, optional) 
#' @param max_image_number (length-1 `character`, optional) Maxium image number of the page where the schedule item is reported
#' @param sort_nulls_last (length-1 `logical`, optional) Toggle that sorts null values last
#' @param max_amount_outstanding_beginning (length-1 `double`, optional) 
#' @param sort_hide_null (length-1 `logical`, optional) Hide null values on sorted column(s).
#' @param min_payment_period (length-1 `double`, optional) 
#' @param max_amount_incurred (length-1 `double`, optional) 
#' @param nature_of_debt (length-1 `character`, optional) 
#' @param per_page (length-1 `list`, optional) The number of results returned per page. Defaults to 20.
#' @param max_amount_outstanding_close (length-1 `double`, optional) 
#' @param candidate_id (length-1 `list`, optional) A unique identifier assigned to each candidate registered with the FEC. If a person runs for several offices, that person will have separate candidate IDs for each office.
#' @param page (length-1 `list`, optional) For paginating through results, starting at page 1
#' @param min_date (length-1 `Date`, optional) Minimum load date
#' @param committee_id (length-1 `list`, optional) A unique identifier assigned to each committee or filer registered with the FEC. In general committee id's begin with the letter C which is followed by eight digits.
#' @param min_amount_outstanding_close (length-1 `double`, optional) 
#' @param api_key (length-1 `character`) API key for https://api.data.gov. Get one at https://api.data.gov/signup.
#' @param max_payment_period (length-1 `double`, optional) 
#' @param min_image_number (length-1 `character`, optional) Minium image number of the page where the schedule item is reported
#' @param min_amount_incurred (length-1 `double`, optional) 
#' @param sort_null_only (length-1 `logical`, optional) Toggle that filters out all rows having sort column that is non-null
#' @param image_number (length-1 `list`, optional) An unique identifier for each page where the electronic or paper filing is reported.
#' @param sort (length-1 `character`, optional) Provide a field to sort by. Use `-` for descending order.
#' @param min_amount_outstanding_beginning (length-1 `double`, optional) 
#' @param max_date (length-1 `Date`, optional) Maximum load date
#' @inheritParams .shared-params
#'
#' @returns `get_schedules_schedule_d()`: The API response.
#' @export
get_schedules_schedule_d <- function(creditor_debtor_name, max_image_number, sort_nulls_last, max_amount_outstanding_beginning, sort_hide_null, min_payment_period, max_amount_incurred, nature_of_debt, per_page, max_amount_outstanding_close, candidate_id, page, min_date, committee_id, min_amount_outstanding_close, max_payment_period, min_image_number, min_amount_incurred, sort_null_only, image_number, sort, min_amount_outstanding_beginning, max_date, api_key = Sys.getenv("FEC_API_KEY"), max_reqs = Inf, max_tries_per_req = 3) {
  req <- req_get_schedules_schedule_d(creditor_debtor_name = creditor_debtor_name, max_image_number = max_image_number, sort_nulls_last = sort_nulls_last, max_amount_outstanding_beginning = max_amount_outstanding_beginning, sort_hide_null = sort_hide_null, min_payment_period = min_payment_period, max_amount_incurred = max_amount_incurred, nature_of_debt = nature_of_debt, per_page = per_page, max_amount_outstanding_close = max_amount_outstanding_close, candidate_id = candidate_id, page = page, min_date = min_date, committee_id = committee_id, min_amount_outstanding_close = min_amount_outstanding_close, max_payment_period = max_payment_period, min_image_number = min_image_number, min_amount_incurred = min_amount_incurred, sort_null_only = sort_null_only, image_number = image_number, sort = sort, min_amount_outstanding_beginning = min_amount_outstanding_beginning, max_date = max_date, api_key = api_key)
  resps <- nectar::req_perform_opinionated(
    req,
    max_reqs = max_reqs,
    max_tries_per_req = max_tries_per_req
  )
  return(nectar::resp_parse(resps))
}

#' @rdname get_schedules_schedule_d
#' @returns `req_get_schedules_schedule_d()`: (`httr2_request`) A [httr2::request()] object.
req_get_schedules_schedule_d <- function(creditor_debtor_name, max_image_number, sort_nulls_last, max_amount_outstanding_beginning, sort_hide_null, min_payment_period, max_amount_incurred, nature_of_debt, per_page, max_amount_outstanding_close, candidate_id, page, min_date, committee_id, min_amount_outstanding_close, max_payment_period, min_image_number, min_amount_incurred, sort_null_only, image_number, sort, min_amount_outstanding_beginning, max_date, api_key = Sys.getenv("FEC_API_KEY")) {
  max_image_number <- stbl::to_chr_scalar(max_image_number)
  sort_nulls_last <- stbl::to_lgl_scalar(sort_nulls_last)
  max_amount_outstanding_beginning <- stbl::to_dbl_scalar(max_amount_outstanding_beginning)
  sort_hide_null <- stbl::to_lgl_scalar(sort_hide_null)
  min_payment_period <- stbl::to_dbl_scalar(min_payment_period)
  max_amount_incurred <- stbl::to_dbl_scalar(max_amount_incurred)
  nature_of_debt <- stbl::to_chr_scalar(nature_of_debt)
  max_amount_outstanding_close <- stbl::to_dbl_scalar(max_amount_outstanding_close)
  min_amount_outstanding_close <- stbl::to_dbl_scalar(min_amount_outstanding_close)
  max_payment_period <- stbl::to_dbl_scalar(max_payment_period)
  min_image_number <- stbl::to_chr_scalar(min_image_number)
  min_amount_incurred <- stbl::to_dbl_scalar(min_amount_incurred)
  sort_null_only <- stbl::to_lgl_scalar(sort_null_only)
  sort <- stbl::to_chr_scalar(sort)
  min_amount_outstanding_beginning <- stbl::to_dbl_scalar(min_amount_outstanding_beginning)
  fec_req_prepare(
    path = "/schedules/schedule_d/",
    method = "get",
    api_key = api_key,
    query = list(creditor_debtor_name = creditor_debtor_name, max_image_number = max_image_number, sort_nulls_last = sort_nulls_last, max_amount_outstanding_beginning = max_amount_outstanding_beginning, sort_hide_null = sort_hide_null, min_payment_period = min_payment_period, max_amount_incurred = max_amount_incurred, nature_of_debt = nature_of_debt, per_page = per_page, max_amount_outstanding_close = max_amount_outstanding_close, candidate_id = candidate_id, page = page, min_date = min_date, committee_id = committee_id, min_amount_outstanding_close = min_amount_outstanding_close, max_payment_period = max_payment_period, min_image_number = min_image_number, min_amount_incurred = min_amount_incurred, sort_null_only = sort_null_only, image_number = image_number, sort = sort, min_amount_outstanding_beginning = min_amount_outstanding_beginning, max_date = max_date),
    tidy_policy = tidy_policy_get_schedules_schedule_d()
  )
}

tidy_policy_get_schedules_schedule_d <- function() {
  spec <- tibblify::tspec_row(
  tibblify::tib_row(
    "pagination",
    .required = FALSE,
    tibblify::tib_int("count", .required = FALSE),
    tibblify::tib_int("page", .required = FALSE),
    tibblify::tib_int("pages", .required = FALSE),
    tibblify::tib_int("per_page", .required = FALSE),
  ),
  tibblify::tib_df(
    "results",
    .required = FALSE,
    tibblify::tib_chr("action_code", .required = FALSE),
    tibblify::tib_chr("action_code_full", .required = FALSE),
    tibblify::tib_dbl("amount_incurred_period", .required = FALSE),
    tibblify::tib_chr("candidate_first_name", .required = FALSE),
    tibblify::tib_chr("candidate_id", .required = FALSE),
    tibblify::tib_chr("candidate_last_name", .required = FALSE),
    tibblify::tib_chr("candidate_name", .required = FALSE),
    tibblify::tib_chr("candidate_office", .required = FALSE),
    tibblify::tib_chr("candidate_office_district", .required = FALSE),
    tibblify::tib_chr("candidate_office_state", .required = FALSE),
    tibblify::tib_chr("candidate_office_state_full", .required = FALSE),
    tibblify::tib_row(
      "committee",
      .required = FALSE,
      tibblify::tib_chr("affiliated_committee_name", .required = FALSE),
      tibblify::tib_chr_vec("candidate_ids", .required = FALSE),
      tibblify::tib_chr("city", .required = FALSE),
      tibblify::tib_chr("committee_id"),
      tibblify::tib_chr("committee_type", .required = FALSE),
      tibblify::tib_chr("committee_type_full", .required = FALSE),
      tibblify::tib_int("cycle"),
      tibblify::tib_int_vec("cycles", .required = FALSE),
      tibblify::tib_int_vec("cycles_has_activity", .required = FALSE),
      tibblify::tib_int_vec("cycles_has_financial", .required = FALSE),
      tibblify::tib_chr("designation", .required = FALSE),
      tibblify::tib_chr("designation_full", .required = FALSE),
      tibblify::tib_chr("filing_frequency", .required = FALSE),
      tibblify::tib_chr("first_f1_date", .required = FALSE),
      tibblify::tib_chr("first_file_date", .required = FALSE),
      tibblify::tib_lgl("is_active", .required = FALSE),
      tibblify::tib_df(
        "jfc_committee",
        .required = FALSE,
        tibblify::tib_chr("joint_committee_id", .required = FALSE),
        tibblify::tib_chr("joint_committee_name", .required = FALSE),
      ),
      tibblify::tib_int("last_cycle_has_activity", .required = FALSE),
      tibblify::tib_int("last_cycle_has_financial", .required = FALSE),
      tibblify::tib_chr("last_f1_date", .required = FALSE),
      tibblify::tib_chr("last_file_date", .required = FALSE),
      tibblify::tib_chr("name", .required = FALSE),
      tibblify::tib_chr("organization_type", .required = FALSE),
      tibblify::tib_chr("organization_type_full", .required = FALSE),
      tibblify::tib_chr("party", .required = FALSE),
      tibblify::tib_chr("party_full", .required = FALSE),
      tibblify::tib_chr("state", .required = FALSE),
      tibblify::tib_chr("state_full", .required = FALSE),
      tibblify::tib_chr("street_1", .required = FALSE),
      tibblify::tib_chr("street_2", .required = FALSE),
      tibblify::tib_chr("treasurer_name", .required = FALSE),
      tibblify::tib_chr("zip", .required = FALSE),
    ),
    tibblify::tib_chr("committee_id", .required = FALSE),
    tibblify::tib_chr("committee_name", .required = FALSE),
    tibblify::tib_chr("conduit_committee_city", .required = FALSE),
    tibblify::tib_chr("conduit_committee_id", .required = FALSE),
    tibblify::tib_chr("conduit_committee_name", .required = FALSE),
    tibblify::tib_chr("conduit_committee_state", .required = FALSE),
    tibblify::tib_chr("conduit_committee_street1", .required = FALSE),
    tibblify::tib_chr("conduit_committee_street2", .required = FALSE),
    tibblify::tib_int("conduit_committee_zip", .required = FALSE),
    tibblify::tib_chr("creditor_debtor_city", .required = FALSE),
    tibblify::tib_chr("creditor_debtor_first_name", .required = FALSE),
    tibblify::tib_chr("creditor_debtor_id", .required = FALSE),
    tibblify::tib_chr("creditor_debtor_last_name", .required = FALSE),
    tibblify::tib_chr("creditor_debtor_middle_name", .required = FALSE),
    tibblify::tib_chr("creditor_debtor_name", .required = FALSE),
    tibblify::tib_chr("creditor_debtor_prefix", .required = FALSE),
    tibblify::tib_chr("creditor_debtor_state", .required = FALSE),
    tibblify::tib_chr("creditor_debtor_street1", .required = FALSE),
    tibblify::tib_chr("creditor_debtor_street2", .required = FALSE),
    tibblify::tib_chr("creditor_debtor_suffix", .required = FALSE),
    tibblify::tib_int("election_cycle", .required = FALSE),
    tibblify::tib_chr("entity_type", .required = FALSE),
    tibblify::tib_int("file_number", .required = FALSE),
    tibblify::tib_chr("filing_form", .required = FALSE),
    tibblify::tib_chr("image_number", .required = FALSE),
    tibblify::tib_chr("line_number", .required = FALSE),
    tibblify::tib_int("link_id", .required = FALSE),
    tibblify::tib_chr("load_date", .required = FALSE),
    tibblify::tib_chr("nature_of_debt", .required = FALSE),
    tibblify::tib_int("original_sub_id", .required = FALSE),
    tibblify::tib_dbl(
      "outstanding_balance_beginning_of_period",
      .required = FALSE,
    ),
    tibblify::tib_dbl("outstanding_balance_close_of_period", .required = FALSE),
    tibblify::tib_dbl("payment_period", .required = FALSE),
    tibblify::tib_chr("pdf_url", .required = FALSE),
    tibblify::tib_chr("report_type", .required = FALSE),
    tibblify::tib_int("report_year", .required = FALSE),
    tibblify::tib_chr("schedule_type", .required = FALSE),
    tibblify::tib_chr("schedule_type_full", .required = FALSE),
    tibblify::tib_chr("sub_id", .required = FALSE),
    tibblify::tib_chr("transaction_id", .required = FALSE),
  ),
)
  nectar::tidy_policy_json_tibblify(spec = spec)
}
