# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions.

#' Get legal search
#'
#' Search legal documents by document type, or across all document types using keywords, parameter values and ranges.
#' 
#' @param hits_returned (length-1 `list`, optional) Number of results to return (max 10)
#' @param af_report_year (length-1 `character`, optional) Admin fine report year
#' @param case_max_open_date (length-1 `Date`, optional) The latest date opened of case
#' @param ao_max_issue_date (length-1 `Date`, optional) Latest issue date of advisory opinion
#' @param case_statutory_citation (length-1 `list`, optional) Statutory citations
#' @param case_respondents (length-1 `character`, optional) Cases respondents
#' @param q (length-1 `character`, optional) Text to search legal documents for
#' @param ao_min_issue_date (length-1 `Date`, optional) Earliest issue date of advisory opinion
#' @param af_max_fd_date (length-1 `Date`, optional) The latest Final Determination date
#' @param from_hit (length-1 `list`, optional) Get results starting from this index
#' @param af_fd_fine_amount (length-1 `list`, optional) Final Determination fine amount
#' @param type (length-1 `character`, optional) Legal Document type to refine search by - statutes - regulations - advisory_opinions - murs - admin_fines
#' @param api_key (length-1 `character`) API key for https://api.data.gov. Get one at https://api.data.gov/signup.
#' @param af_name (length-1 `list`, optional) Admin fine committee name
#' @param ao_requestor_type (length-1 `list`, optional) Code of the advisory opinion requestor type.
#' @param ao_statutory_citation (length-1 `list`, optional) Statutory citations
#' @param ao_entity_name (length-1 `list`, optional) Name of commenter or representative
#' @param mur_type (length-1 `character`, optional) Type of MUR : current or archived
#' @param ao_regulatory_citation (length-1 `list`, optional) Regulatory citations
#' @param af_committee_id (length-1 `character`, optional) Admin fine committee ID
#' @param ao_requestor (length-1 `character`, optional) The requestor of the advisory opinion
#' @param case_citation_require_all (length-1 `logical`, optional) Require all citations to be in document (default behavior is any)
#' @param af_min_fd_date (length-1 `Date`, optional) The earliest Final Determination date
#' @param ao_is_pending (length-1 `logical`, optional) AO is pending
#' @param af_rtb_fine_amount (length-1 `list`, optional) Reason to Believe fine amount
#' @param case_election_cycles (length-1 `list`, optional) Cases election cycles
#' @param ao_category (length-1 `list`, optional) Category of the document
#' @param ao_citation_require_all (length-1 `logical`, optional) Require all citations to be in document (default behavior is any)
#' @param case_dispositions (length-1 `list`, optional) Cases dispositions
#' @param af_max_rtb_date (length-1 `Date`, optional) The latest Reason to Believe date
#' @param case_min_open_date (length-1 `Date`, optional) The earliest date opened of case
#' @param case_max_close_date (length-1 `Date`, optional) The latest date closed of case
#' @param ao_min_request_date (length-1 `Date`, optional) Earliest request date of advisory opinion
#' @param ao_status (length-1 `character`, optional) Status of AO (pending, withdrawn, or final)
#' @param case_doc_category_id (length-1 `list`, optional) Select one or more case_doc_category_id to filter by corresponding CASE_DOCUMENT_CATEGORY: - 1 - Conciliation Agreements - 2 - Complaint, Responses, Designation of Counsel and Extensions of Timee - 3 - General Counsel Reports, Briefs, Notifications and Responses - 4 - Certifications - 5 - Civil Penalties, Disgorgements and Other Payments - 6 - Statements of Reasons
#' @param af_min_rtb_date (length-1 `Date`, optional) The earliest Reason to Believe date
#' @param ao_name (length-1 `list`, optional) Force advisory opinion name
#' @param case_regulatory_citation (length-1 `list`, optional) Regulatory citations
#' @param ao_no (length-1 `list`, optional) Force advisory opinion number
#' @param case_min_close_date (length-1 `Date`, optional) The earliest date closed of case
#' @param sort (length-1 `character`, optional) Provide a field to sort by. Use `-` for descending order. ex: `-case_no`
#' @param ao_max_request_date (length-1 `Date`, optional) Latest request date of advisory opinion
#' @param case_no (length-1 `list`, optional) Enforcement matter case number
#' @inheritParams .shared-params
#'
#' @returns `get_legal_search()`: Legal search results
#' @keywords internal
get_legal_search <- function(hits_returned, af_report_year, case_max_open_date, ao_max_issue_date, case_statutory_citation, case_respondents, q, ao_min_issue_date, af_max_fd_date, from_hit, af_fd_fine_amount, type, af_name, ao_requestor_type, ao_statutory_citation, ao_entity_name, mur_type, ao_regulatory_citation, af_committee_id, ao_requestor, case_citation_require_all, af_min_fd_date, ao_is_pending, af_rtb_fine_amount, case_election_cycles, ao_category, ao_citation_require_all, case_dispositions, af_max_rtb_date, case_min_open_date, case_max_close_date, ao_min_request_date, ao_status, case_doc_category_id, af_min_rtb_date, ao_name, case_regulatory_citation, ao_no, case_min_close_date, sort, ao_max_request_date, case_no, api_key = Sys.getenv("FEC_API_KEY"), max_reqs = Inf, max_tries_per_req = 3) {
  req <- req_get_legal_search(hits_returned = hits_returned, af_report_year = af_report_year, case_max_open_date = case_max_open_date, ao_max_issue_date = ao_max_issue_date, case_statutory_citation = case_statutory_citation, case_respondents = case_respondents, q = q, ao_min_issue_date = ao_min_issue_date, af_max_fd_date = af_max_fd_date, from_hit = from_hit, af_fd_fine_amount = af_fd_fine_amount, type = type, af_name = af_name, ao_requestor_type = ao_requestor_type, ao_statutory_citation = ao_statutory_citation, ao_entity_name = ao_entity_name, mur_type = mur_type, ao_regulatory_citation = ao_regulatory_citation, af_committee_id = af_committee_id, ao_requestor = ao_requestor, case_citation_require_all = case_citation_require_all, af_min_fd_date = af_min_fd_date, ao_is_pending = ao_is_pending, af_rtb_fine_amount = af_rtb_fine_amount, case_election_cycles = case_election_cycles, ao_category = ao_category, ao_citation_require_all = ao_citation_require_all, case_dispositions = case_dispositions, af_max_rtb_date = af_max_rtb_date, case_min_open_date = case_min_open_date, case_max_close_date = case_max_close_date, ao_min_request_date = ao_min_request_date, ao_status = ao_status, case_doc_category_id = case_doc_category_id, af_min_rtb_date = af_min_rtb_date, ao_name = ao_name, case_regulatory_citation = case_regulatory_citation, ao_no = ao_no, case_min_close_date = case_min_close_date, sort = sort, ao_max_request_date = ao_max_request_date, case_no = case_no, api_key = api_key)
  resps <- nectar::req_perform_opinionated(
    req,
    max_reqs = max_reqs,
    max_tries_per_req = max_tries_per_req
  )
  return(nectar::resp_parse(resps))
}

#' @rdname get_legal_search
#' @returns `req_get_legal_search()`: (`httr2_request`) A [httr2::request()] object.
#' @export
req_get_legal_search <- function(hits_returned, af_report_year, case_max_open_date, ao_max_issue_date, case_statutory_citation, case_respondents, q, ao_min_issue_date, af_max_fd_date, from_hit, af_fd_fine_amount, type, af_name, ao_requestor_type, ao_statutory_citation, ao_entity_name, mur_type, ao_regulatory_citation, af_committee_id, ao_requestor, case_citation_require_all, af_min_fd_date, ao_is_pending, af_rtb_fine_amount, case_election_cycles, ao_category, ao_citation_require_all, case_dispositions, af_max_rtb_date, case_min_open_date, case_max_close_date, ao_min_request_date, ao_status, case_doc_category_id, af_min_rtb_date, ao_name, case_regulatory_citation, ao_no, case_min_close_date, sort, ao_max_request_date, case_no, api_key = Sys.getenv("FEC_API_KEY")) {
  af_report_year <- stbl::to_chr_scalar(af_report_year)
  case_respondents <- stbl::to_chr_scalar(case_respondents)
  q <- stbl::to_chr_scalar(q)
  type <- stbl::to_chr_scalar(type)
  mur_type <- stbl::to_chr_scalar(mur_type)
  af_committee_id <- stbl::to_chr_scalar(af_committee_id)
  ao_requestor <- stbl::to_chr_scalar(ao_requestor)
  case_citation_require_all <- stbl::to_lgl_scalar(case_citation_require_all)
  ao_is_pending <- stbl::to_lgl_scalar(ao_is_pending)
  ao_citation_require_all <- stbl::to_lgl_scalar(ao_citation_require_all)
  ao_status <- stbl::to_chr_scalar(ao_status)
  sort <- stbl::to_chr_scalar(sort)
  fec_req_prepare(
    path = "/legal/search/",
    method = "get",
    api_key = api_key,
    query = list(hits_returned = hits_returned, af_report_year = af_report_year, case_max_open_date = case_max_open_date, ao_max_issue_date = ao_max_issue_date, case_statutory_citation = case_statutory_citation, case_respondents = case_respondents, q = q, ao_min_issue_date = ao_min_issue_date, af_max_fd_date = af_max_fd_date, from_hit = from_hit, af_fd_fine_amount = af_fd_fine_amount, type = type, af_name = af_name, ao_requestor_type = ao_requestor_type, ao_statutory_citation = ao_statutory_citation, ao_entity_name = ao_entity_name, mur_type = mur_type, ao_regulatory_citation = ao_regulatory_citation, af_committee_id = af_committee_id, ao_requestor = ao_requestor, case_citation_require_all = case_citation_require_all, af_min_fd_date = af_min_fd_date, ao_is_pending = ao_is_pending, af_rtb_fine_amount = af_rtb_fine_amount, case_election_cycles = case_election_cycles, ao_category = ao_category, ao_citation_require_all = ao_citation_require_all, case_dispositions = case_dispositions, af_max_rtb_date = af_max_rtb_date, case_min_open_date = case_min_open_date, case_max_close_date = case_max_close_date, ao_min_request_date = ao_min_request_date, ao_status = ao_status, case_doc_category_id = case_doc_category_id, af_min_rtb_date = af_min_rtb_date, ao_name = ao_name, case_regulatory_citation = case_regulatory_citation, ao_no = ao_no, case_min_close_date = case_min_close_date, sort = sort, ao_max_request_date = ao_max_request_date, case_no = case_no),
    tidy_policy = tidy_policy_get_legal_search()
  )
}

#' @rdname get_legal_search
#' @returns `tidy_policy_get_legal_search()`: (`nectar_tidy_policy`) 
#'   A list like the ones returned by [nectar::tidy_policy_prepare()].
#' @export
tidy_policy_get_legal_search <- function() {
  spec <- tibblify::tspec_row(
  tibblify::tib_df(
    "admin_fines",
    .required = FALSE,
    tibblify::tib_chr("challenge_outcome", .required = FALSE),
    tibblify::tib_chr("challenge_receipt_date", .required = FALSE),
    tibblify::tib_dbl("check_amount", .required = FALSE),
    tibblify::tib_df(
      "commission_votes",
      .required = FALSE,
      tibblify::tib_chr("action", .required = FALSE),
      tibblify::tib_chr("vote_date", .required = FALSE),
    ),
    tibblify::tib_chr("committee_id", .required = FALSE),
    tibblify::tib_chr("doc_id", .required = FALSE),
    tibblify::tib_row(
      "document_highlights",
      .required = FALSE,
    ),
    tibblify::tib_df(
      "documents",
      .required = FALSE,
      tibblify::tib_chr("category", .required = FALSE),
      tibblify::tib_chr("description", .required = FALSE),
      tibblify::tib_chr("document_date", .required = FALSE),
      tibblify::tib_int("document_id", .required = FALSE),
      tibblify::tib_int("length", .required = FALSE),
      tibblify::tib_chr("url", .required = FALSE),
    ),
    tibblify::tib_dbl("final_determination_amount", .required = FALSE),
    tibblify::tib_chr("final_determination_date", .required = FALSE),
    tibblify::tib_chr_vec("highlights", .required = FALSE),
    tibblify::tib_chr("name", .required = FALSE),
    tibblify::tib_chr("FALSE", .required = FALSE),
    tibblify::tib_chr("petition_court_decision_date", .required = FALSE),
    tibblify::tib_chr("petition_court_filing_date", .required = FALSE),
    tibblify::tib_chr("reason_to_believe_action_date", .required = FALSE),
    tibblify::tib_dbl("reason_to_believe_fine_amount", .required = FALSE),
    tibblify::tib_chr("report_type", .required = FALSE),
    tibblify::tib_chr("report_year", .required = FALSE),
    tibblify::tib_dbl("treasury_referral_amount", .required = FALSE),
    tibblify::tib_chr("treasury_referral_date", .required = FALSE),
    tibblify::tib_chr("url", .required = FALSE),
  ),
  tibblify::tib_df(
    "adrs",
    .required = FALSE,
    tibblify::tib_chr("close_date", .required = FALSE),
    tibblify::tib_df(
      "commission_votes",
      .required = FALSE,
      tibblify::tib_chr("action", .required = FALSE),
      tibblify::tib_chr("vote_date", .required = FALSE),
    ),
    tibblify::tib_df(
      "dispositions",
      .required = FALSE,
      tibblify::tib_df(
        "citations",
        .required = FALSE,
        tibblify::tib_chr("text", .required = FALSE),
        tibblify::tib_chr("title", .required = FALSE),
        tibblify::tib_chr("type", .required = FALSE),
        tibblify::tib_chr("url", .required = FALSE),
      ),
      tibblify::tib_chr("disposition", .required = FALSE),
      tibblify::tib_dbl("penalty", .required = FALSE),
      tibblify::tib_chr("respondent", .required = FALSE),
    ),
    tibblify::tib_chr("doc_id", .required = FALSE),
    tibblify::tib_row(
      "document_highlights",
      .required = FALSE,
    ),
    tibblify::tib_df(
      "documents",
      .required = FALSE,
      tibblify::tib_chr("category", .required = FALSE),
      tibblify::tib_chr("description", .required = FALSE),
      tibblify::tib_chr("document_date", .required = FALSE),
      tibblify::tib_int("document_id", .required = FALSE),
      tibblify::tib_int("length", .required = FALSE),
      tibblify::tib_chr("url", .required = FALSE),
    ),
    tibblify::tib_int("election_cycles", .required = FALSE),
    tibblify::tib_chr_vec("highlights", .required = FALSE),
    tibblify::tib_chr("name", .required = FALSE),
    tibblify::tib_chr("FALSE", .required = FALSE),
    tibblify::tib_chr("open_date", .required = FALSE),
    tibblify::tib_df(
      "participants",
      .required = FALSE,
      tibblify::tib_row(
        "citations",
        .required = FALSE,
      ),
      tibblify::tib_chr("name", .required = FALSE),
      tibblify::tib_chr("role", .required = FALSE),
    ),
    tibblify::tib_chr_vec("respondents", .required = FALSE),
    tibblify::tib_chr_vec("subjects", .required = FALSE),
    tibblify::tib_chr("url", .required = FALSE),
  ),
  tibblify::tib_df(
    "advisory_opinions",
    .required = FALSE,
    tibblify::tib_df(
      "ao_citations",
      .required = FALSE,
      tibblify::tib_chr("name", .required = FALSE),
      tibblify::tib_chr("FALSE", .required = FALSE),
    ),
    tibblify::tib_df(
      "aos_cited_by",
      .required = FALSE,
      tibblify::tib_chr("name", .required = FALSE),
      tibblify::tib_chr("FALSE", .required = FALSE),
    ),
    tibblify::tib_chr_vec("commenter_names", .required = FALSE),
    tibblify::tib_row(
      "document_highlights",
      .required = FALSE,
    ),
    tibblify::tib_df(
      "documents",
      .required = FALSE,
      tibblify::tib_chr("category", .required = FALSE),
      tibblify::tib_chr("date", .required = FALSE),
      tibblify::tib_chr("description", .required = FALSE),
      tibblify::tib_int("document_id", .required = FALSE),
      tibblify::tib_chr("url", .required = FALSE),
    ),
    tibblify::tib_df(
      "entities",
      .required = FALSE,
      tibblify::tib_chr("name", .required = FALSE),
      tibblify::tib_chr("role", .required = FALSE),
      tibblify::tib_chr("type", .required = FALSE),
    ),
    tibblify::tib_chr_vec("highlights", .required = FALSE),
    tibblify::tib_lgl("is_pending", .required = FALSE),
    tibblify::tib_chr("issue_date", .required = FALSE),
    tibblify::tib_chr("name", .required = FALSE),
    tibblify::tib_chr("FALSE", .required = FALSE),
    tibblify::tib_df(
      "regulatory_citations",
      .required = FALSE,
      tibblify::tib_int("part", .required = FALSE),
      tibblify::tib_int("section", .required = FALSE),
      tibblify::tib_int("title", .required = FALSE),
    ),
    tibblify::tib_chr_vec("representative_names", .required = FALSE),
    tibblify::tib_chr("request_date", .required = FALSE),
    tibblify::tib_chr_vec("requestor_names", .required = FALSE),
    tibblify::tib_chr_vec("requestor_types", .required = FALSE),
    tibblify::tib_chr("status", .required = FALSE),
    tibblify::tib_df(
      "statutory_citations",
      .required = FALSE,
      tibblify::tib_chr("section", .required = FALSE),
      tibblify::tib_int("title", .required = FALSE),
    ),
    tibblify::tib_chr("summary", .required = FALSE),
  ),
  tibblify::tib_df(
    "murs",
    .required = FALSE,
    tibblify::tib_chr("close_date", .required = FALSE),
    tibblify::tib_df(
      "commission_votes",
      .required = FALSE,
      tibblify::tib_chr("action", .required = FALSE),
      tibblify::tib_chr("vote_date", .required = FALSE),
    ),
    tibblify::tib_df(
      "dispositions",
      .required = FALSE,
      tibblify::tib_df(
        "citations",
        .required = FALSE,
        tibblify::tib_chr("text", .required = FALSE),
        tibblify::tib_chr("title", .required = FALSE),
        tibblify::tib_chr("type", .required = FALSE),
        tibblify::tib_chr("url", .required = FALSE),
      ),
      tibblify::tib_chr("disposition", .required = FALSE),
      tibblify::tib_dbl("penalty", .required = FALSE),
      tibblify::tib_chr("respondent", .required = FALSE),
    ),
    tibblify::tib_chr("doc_id", .required = FALSE),
    tibblify::tib_row(
      "document_highlights",
      .required = FALSE,
    ),
    tibblify::tib_df(
      "documents",
      .required = FALSE,
      tibblify::tib_chr("category", .required = FALSE),
      tibblify::tib_chr("description", .required = FALSE),
      tibblify::tib_chr("document_date", .required = FALSE),
      tibblify::tib_int("document_id", .required = FALSE),
      tibblify::tib_int("length", .required = FALSE),
      tibblify::tib_chr("url", .required = FALSE),
    ),
    tibblify::tib_int("election_cycles", .required = FALSE),
    tibblify::tib_chr_vec("highlights", .required = FALSE),
    tibblify::tib_chr("mur_type", .required = FALSE),
    tibblify::tib_chr("name", .required = FALSE),
    tibblify::tib_chr("FALSE", .required = FALSE),
    tibblify::tib_chr("open_date", .required = FALSE),
    tibblify::tib_df(
      "participants",
      .required = FALSE,
      tibblify::tib_row(
        "citations",
        .required = FALSE,
      ),
      tibblify::tib_chr("name", .required = FALSE),
      tibblify::tib_chr("role", .required = FALSE),
    ),
    tibblify::tib_chr_vec("respondents", .required = FALSE),
    tibblify::tib_chr_vec("subjects", .required = FALSE),
    tibblify::tib_chr("url", .required = FALSE),
  ),
  tibblify::tib_df(
    "regulations",
    .required = FALSE,
    tibblify::tib_chr("doc_id", .required = FALSE),
    tibblify::tib_row(
      "document_highlights",
      .required = FALSE,
    ),
    tibblify::tib_chr_vec("highlights", .required = FALSE),
    tibblify::tib_chr("name", .required = FALSE),
    tibblify::tib_chr("FALSE", .required = FALSE),
    tibblify::tib_chr("url", .required = FALSE),
  ),
  tibblify::tib_df(
    "statutes",
    .required = FALSE,
    tibblify::tib_chr("chapter", .required = FALSE),
    tibblify::tib_chr("doc_id", .required = FALSE),
    tibblify::tib_row(
      "document_highlights",
      .required = FALSE,
    ),
    tibblify::tib_chr_vec("highlights", .required = FALSE),
    tibblify::tib_chr("name", .required = FALSE),
    tibblify::tib_chr("FALSE", .required = FALSE),
    tibblify::tib_chr("title", .required = FALSE),
    tibblify::tib_chr("url", .required = FALSE),
  ),
  tibblify::tib_int("total_admin_fines", .required = FALSE),
  tibblify::tib_int("total_adrs", .required = FALSE),
  tibblify::tib_int("total_advisory_opinions", .required = FALSE),
  tibblify::tib_int("total_all", .required = FALSE),
  tibblify::tib_int("total_murs", .required = FALSE),
  tibblify::tib_int("total_regulations", .required = FALSE),
  tibblify::tib_int("total_statutes", .required = FALSE),
)
  nectar::tidy_policy_json_tibblify(spec = spec)
}
