# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions.

#' Get names audit candidates
#'
#' Search for candidates or committees by name. If you're looking for information on a particular person or group, using a name to find the `candidate_id` or `committee_id` on this endpoint can be a helpful first step.
#' 
#' @param api_key (length-1 `character`) API key for https://api.data.gov. Get one at https://api.data.gov/signup.
#' @param q (length-1 `list`) Name (candidate or committee) to search for
#' @inheritParams .shared-params
#'
#' @returns `get_names_audit_candidates()`: The API response.
#' @keywords internal
get_names_audit_candidates <- function(q, api_key = Sys.getenv("FEC_API_KEY"), max_reqs = Inf, max_tries_per_req = 3) {
  req <- req_get_names_audit_candidates(q = q, api_key = api_key)
  resps <- nectar::req_perform_opinionated(
    req,
    max_reqs = max_reqs,
    max_tries_per_req = max_tries_per_req
  )
  return(nectar::resp_parse(resps))
}

#' @rdname get_names_audit_candidates
#' @returns `req_get_names_audit_candidates()`: (`httr2_request`) A [httr2::request()] object.
#' @export
req_get_names_audit_candidates <- function(q, api_key = Sys.getenv("FEC_API_KEY")) {
  fec_req_prepare(
    path = "/names/audit_candidates/",
    method = "get",
    api_key = api_key,
    query = list(q = q),
    tidy_policy = tidy_policy_get_names_audit_candidates()
  )
}

#' @rdname get_names_audit_candidates
#' @returns `tidy_policy_get_names_audit_candidates()`: (`nectar_tidy_policy`) 
#'   A list like the ones returned by [nectar::tidy_policy_prepare()].
#' @export
tidy_policy_get_names_audit_candidates <- function() {
  spec <- tibblify::tspec_df(
  tibblify::tib_chr("id", .required = FALSE),
  tibblify::tib_chr("name", .required = FALSE),
)
  nectar::tidy_policy_json_tibblify(spec = spec, subset_path = "results")
}
