# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions.

#' Search things
#'
#' Search for things.
#' 
#' @param x_auth_token (length-1 `character`) Authentication token
#' @param session_id (length-1 `character`) Session identifier
#' @param q (length-1 `character`) Search query
#' @inheritParams .shared-params
#'
#' @returns `search_things()`: The API response.
#' @keywords internal
search_things <- function(x_auth_token, session_id, q, max_reqs = Inf, max_tries_per_req = 3) {
  req <- req_search_things(x_auth_token = x_auth_token, session_id = session_id, q = q)
  resps <- nectar::req_perform_opinionated(
    req,
    max_reqs = max_reqs,
    max_tries_per_req = max_tries_per_req
  )
  return(nectar::resp_parse(resps))
}

#' @rdname search_things
#' @returns `req_search_things()`: (`httr2_request`) A [httr2::request()] object.
#' @export
req_search_things <- function(x_auth_token, session_id, q) {
  x_auth_token <- stbl::to_chr_scalar(x_auth_token)
  session_id <- stbl::to_chr_scalar(session_id)
  q <- stbl::to_chr_scalar(q)
  test_req_prepare(
    path = "/things",
    method = "get",
    query = list(q = q),
    header = list(x_auth_token = x_auth_token),
    cookie = list(session_id = session_id),
    tidy_policy = tidy_policy_search_things()
  )
}

#' @rdname search_things
#' @returns `tidy_policy_search_things()`: (`nectar_tidy_policy`) 
#'   A list like the ones returned by [nectar::tidy_policy_prepare()].
#' @export
tidy_policy_search_things <- function() {
  nectar::tidy_policy_body_auto()
}
