# These tests were generated by the {beekeeper} package, based on the paths
# element from the source API description. You will likely need to supply
# arguments for the tests to succeed. We recommend expanding these tests to
# check for specific expectations, rather than simply using a snapshot.

with_mock_dir("api/path/audit/get_names_audit_committees", {
  test_that("get_names_audit_committees() returns expected result", {
    beekeeper::skip_if_not_exported("get_names_audit_committees")
    expect_snapshot({
      test_result <- get_names_audit_committees(q)
      test_result
    })
  })

})
