# These tests were generated by the {beekeeper} package, based on the paths
# element from the source API description. You will likely need to supply
# arguments for the tests to succeed. We recommend expanding these tests to
# check for specific expectations, rather than simply using a snapshot.

with_mock_dir("api/path/debts/get_schedules_schedule_d_sub_id", {
  test_that("get_schedules_schedule_d_sub_id() returns expected result", {
    skip_if_not_exported("get_schedules_schedule_d_sub_id")
    expect_snapshot({
      test_result <- get_schedules_schedule_d_sub_id(sort_nulls_last, per_page, sort_null_only, sort_hide_null, sort, page, sub_id)
      test_result
    })
  })

})
