# These tests were generated by the {beekeeper} package, based on the paths
# element from the source API description. You will likely need to supply
# arguments for the tests to succeed. We recommend expanding these tests to
# check for specific expectations, rather than simply using a snapshot.

with_mock_dir("api/path/audit/get_audit_primary_category", {
  test_that("get_audit_primary_category() returns expected result (#123)", {
    expect_snapshot({
      test_result <- get_audit_primary_category(sort_nulls_last, page, primary_category_name, sort_hide_null, primary_category_id, sort_null_only, per_page, sort)
      test_result
    })
  })

})
