# These tests were generated by the {beekeeper} package, based on the paths
# element from the source API description. You will likely need to supply
# arguments for the tests to succeed. We recommend expanding these tests to
# check for specific expectations, rather than simply using a snapshot.

with_mock_dir("api/path/audit/get_names_audit_candidates", {
  test_that("get_names_audit_candidates() returns expected result", {
    expect_snapshot({
      test_result <- get_names_audit_candidates(q)
      test_result
    })
  })

})
