# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions.

#' Get legal search
#'
#' Search legal documents by document type, or across all document types using keywords, parameter values and ranges.
#'
#' @param hits_returned (length-1 \code{\link[base:list]{list}}, optional) Number of results to return (max 10)
#' @param af_report_year (length-1 \code{\link[base:character]{character}}, optional) Admin fine report year
#' @param case_max_open_date (length-1 \code{\link[base:Date]{Date}}, optional) The latest date opened of case
#' @param ao_max_issue_date (length-1 \code{\link[base:Date]{Date}}, optional) Latest issue date of advisory opinion
#' @param case_statutory_citation (length-1 \code{\link[base:list]{list}}, optional) Statutory citations
#' @param case_respondents (length-1 \code{\link[base:character]{character}}, optional) Cases respondents
#' @param q (length-1 \code{\link[base:character]{character}}, optional) Text to search legal documents for
#' @param ao_min_issue_date (length-1 \code{\link[base:Date]{Date}}, optional) Earliest issue date of advisory opinion
#' @param af_max_fd_date (length-1 \code{\link[base:Date]{Date}}, optional) The latest Final Determination date
#' @param from_hit (length-1 \code{\link[base:list]{list}}, optional) Get results starting from this index
#' @param af_fd_fine_amount (length-1 \code{\link[base:list]{list}}, optional) Final Determination fine amount
#' @param type (length-1 \code{\link[base:character]{character}}, optional) Legal Document type to refine search by - statutes - regulations - advisory_opinions - murs - admin_fines
#' @param api_key (length-1 \code{\link[base:character]{character}}) API key for https://api.data.gov. Get one at https://api.data.gov/signup.
#' @param af_name (length-1 \code{\link[base:list]{list}}, optional) Admin fine committee name
#' @param ao_requestor_type (length-1 \code{\link[base:list]{list}}, optional) Code of the advisory opinion requestor type.
#' @param ao_statutory_citation (length-1 \code{\link[base:list]{list}}, optional) Statutory citations
#' @param ao_entity_name (length-1 \code{\link[base:list]{list}}, optional) Name of commenter or representative
#' @param mur_type (length-1 \code{\link[base:character]{character}}, optional) Type of MUR : current or archived
#' @param ao_regulatory_citation (length-1 \code{\link[base:list]{list}}, optional) Regulatory citations
#' @param af_committee_id (length-1 \code{\link[base:character]{character}}, optional) Admin fine committee ID
#' @param ao_requestor (length-1 \code{\link[base:character]{character}}, optional) The requestor of the advisory opinion
#' @param case_citation_require_all (length-1 \code{\link[base:logical]{logical}}, optional) Require all citations to be in document (default behavior is any)
#' @param af_min_fd_date (length-1 \code{\link[base:Date]{Date}}, optional) The earliest Final Determination date
#' @param ao_is_pending (length-1 \code{\link[base:logical]{logical}}, optional) AO is pending
#' @param af_rtb_fine_amount (length-1 \code{\link[base:list]{list}}, optional) Reason to Believe fine amount
#' @param case_election_cycles (length-1 \code{\link[base:list]{list}}, optional) Cases election cycles
#' @param ao_category (length-1 \code{\link[base:list]{list}}, optional) Category of the document
#' @param ao_citation_require_all (length-1 \code{\link[base:logical]{logical}}, optional) Require all citations to be in document (default behavior is any)
#' @param case_dispositions (length-1 \code{\link[base:list]{list}}, optional) Cases dispositions
#' @param af_max_rtb_date (length-1 \code{\link[base:Date]{Date}}, optional) The latest Reason to Believe date
#' @param case_min_open_date (length-1 \code{\link[base:Date]{Date}}, optional) The earliest date opened of case
#' @param case_max_close_date (length-1 \code{\link[base:Date]{Date}}, optional) The latest date closed of case
#' @param ao_min_request_date (length-1 \code{\link[base:Date]{Date}}, optional) Earliest request date of advisory opinion
#' @param ao_status (length-1 \code{\link[base:character]{character}}, optional) Status of AO (pending, withdrawn, or final)
#' @param case_doc_category_id (length-1 \code{\link[base:list]{list}}, optional) Select one or more case_doc_category_id to filter by corresponding CASE_DOCUMENT_CATEGORY: - 1 - Conciliation Agreements - 2 - Complaint, Responses, Designation of Counsel and Extensions of Timee - 3 - General Counsel Reports, Briefs, Notifications and Responses - 4 - Certifications - 5 - Civil Penalties, Disgorgements and Other Payments - 6 - Statements of Reasons
#' @param af_min_rtb_date (length-1 \code{\link[base:Date]{Date}}, optional) The earliest Reason to Believe date
#' @param ao_name (length-1 \code{\link[base:list]{list}}, optional) Force advisory opinion name
#' @param case_regulatory_citation (length-1 \code{\link[base:list]{list}}, optional) Regulatory citations
#' @param ao_no (length-1 \code{\link[base:list]{list}}, optional) Force advisory opinion number
#' @param case_min_close_date (length-1 \code{\link[base:Date]{Date}}, optional) The earliest date closed of case
#' @param sort (length-1 \code{\link[base:character]{character}}, optional) Provide a field to sort by. Use `-` for descending order. ex: `-case_no`
#' @param ao_max_request_date (length-1 \code{\link[base:Date]{Date}}, optional) Latest request date of advisory opinion
#' @param case_no (length-1 \code{\link[base:list]{list}}, optional) Enforcement matter case number
#' @inheritParams .shared-params
#'
#' @returns `fec_get_legal_search()`: The API response.
#' @export
fec_get_legal_search <- function(
  hits_returned,
  af_report_year,
  case_max_open_date,
  ao_max_issue_date,
  case_statutory_citation,
  case_respondents,
  q,
  ao_min_issue_date,
  af_max_fd_date,
  from_hit,
  af_fd_fine_amount,
  type,
  af_name,
  ao_requestor_type,
  ao_statutory_citation,
  ao_entity_name,
  mur_type,
  ao_regulatory_citation,
  af_committee_id,
  ao_requestor,
  case_citation_require_all,
  af_min_fd_date,
  ao_is_pending,
  af_rtb_fine_amount,
  case_election_cycles,
  ao_category,
  ao_citation_require_all,
  case_dispositions,
  af_max_rtb_date,
  case_min_open_date,
  case_max_close_date,
  ao_min_request_date,
  ao_status,
  case_doc_category_id,
  af_min_rtb_date,
  ao_name,
  case_regulatory_citation,
  ao_no,
  case_min_close_date,
  sort,
  ao_max_request_date,
  case_no,
  api_key = Sys.getenv("FEC_API_KEY"),
  max_reqs = Inf,
  max_tries_per_req = 3
) {
  req <- req_fec_get_legal_search(
    hits_returned = hits_returned,
    af_report_year = af_report_year,
    case_max_open_date = case_max_open_date,
    ao_max_issue_date = ao_max_issue_date,
    case_statutory_citation = case_statutory_citation,
    case_respondents = case_respondents,
    q = q,
    ao_min_issue_date = ao_min_issue_date,
    af_max_fd_date = af_max_fd_date,
    from_hit = from_hit,
    af_fd_fine_amount = af_fd_fine_amount,
    type = type,
    af_name = af_name,
    ao_requestor_type = ao_requestor_type,
    ao_statutory_citation = ao_statutory_citation,
    ao_entity_name = ao_entity_name,
    mur_type = mur_type,
    ao_regulatory_citation = ao_regulatory_citation,
    af_committee_id = af_committee_id,
    ao_requestor = ao_requestor,
    case_citation_require_all = case_citation_require_all,
    af_min_fd_date = af_min_fd_date,
    ao_is_pending = ao_is_pending,
    af_rtb_fine_amount = af_rtb_fine_amount,
    case_election_cycles = case_election_cycles,
    ao_category = ao_category,
    ao_citation_require_all = ao_citation_require_all,
    case_dispositions = case_dispositions,
    af_max_rtb_date = af_max_rtb_date,
    case_min_open_date = case_min_open_date,
    case_max_close_date = case_max_close_date,
    ao_min_request_date = ao_min_request_date,
    ao_status = ao_status,
    case_doc_category_id = case_doc_category_id,
    af_min_rtb_date = af_min_rtb_date,
    ao_name = ao_name,
    case_regulatory_citation = case_regulatory_citation,
    ao_no = ao_no,
    case_min_close_date = case_min_close_date,
    sort = sort,
    ao_max_request_date = ao_max_request_date,
    case_no = case_no,
    api_key = api_key
  )
  resps <- nectar::req_perform_opinionated(
    req,
    max_reqs = max_reqs,
    max_tries_per_req = max_tries_per_req
  )
  return(nectar::resp_parse(resps))
}

#' @rdname fec_get_legal_search
#' @returns `req_fec_get_legal_search()`: A `httr2_request` request object.
req_fec_get_legal_search <- function(
  hits_returned,
  af_report_year,
  case_max_open_date,
  ao_max_issue_date,
  case_statutory_citation,
  case_respondents,
  q,
  ao_min_issue_date,
  af_max_fd_date,
  from_hit,
  af_fd_fine_amount,
  type,
  af_name,
  ao_requestor_type,
  ao_statutory_citation,
  ao_entity_name,
  mur_type,
  ao_regulatory_citation,
  af_committee_id,
  ao_requestor,
  case_citation_require_all,
  af_min_fd_date,
  ao_is_pending,
  af_rtb_fine_amount,
  case_election_cycles,
  ao_category,
  ao_citation_require_all,
  case_dispositions,
  af_max_rtb_date,
  case_min_open_date,
  case_max_close_date,
  ao_min_request_date,
  ao_status,
  case_doc_category_id,
  af_min_rtb_date,
  ao_name,
  case_regulatory_citation,
  ao_no,
  case_min_close_date,
  sort,
  ao_max_request_date,
  case_no,
  api_key = Sys.getenv("FEC_API_KEY")
) {
  fec_req_prepare(
    path = "/legal/search/",
    method = "get",
    api_key = api_key,
    query = list(
      hits_returned = hits_returned,
      af_report_year = af_report_year,
      case_max_open_date = case_max_open_date,
      ao_max_issue_date = ao_max_issue_date,
      case_statutory_citation = case_statutory_citation,
      case_respondents = case_respondents,
      q = q,
      ao_min_issue_date = ao_min_issue_date,
      af_max_fd_date = af_max_fd_date,
      from_hit = from_hit,
      af_fd_fine_amount = af_fd_fine_amount,
      type = type,
      af_name = af_name,
      ao_requestor_type = ao_requestor_type,
      ao_statutory_citation = ao_statutory_citation,
      ao_entity_name = ao_entity_name,
      mur_type = mur_type,
      ao_regulatory_citation = ao_regulatory_citation,
      af_committee_id = af_committee_id,
      ao_requestor = ao_requestor,
      case_citation_require_all = case_citation_require_all,
      af_min_fd_date = af_min_fd_date,
      ao_is_pending = ao_is_pending,
      af_rtb_fine_amount = af_rtb_fine_amount,
      case_election_cycles = case_election_cycles,
      ao_category = ao_category,
      ao_citation_require_all = ao_citation_require_all,
      case_dispositions = case_dispositions,
      af_max_rtb_date = af_max_rtb_date,
      case_min_open_date = case_min_open_date,
      case_max_close_date = case_max_close_date,
      ao_min_request_date = ao_min_request_date,
      ao_status = ao_status,
      case_doc_category_id = case_doc_category_id,
      af_min_rtb_date = af_min_rtb_date,
      ao_name = ao_name,
      case_regulatory_citation = case_regulatory_citation,
      ao_no = ao_no,
      case_min_close_date = case_min_close_date,
      sort = sort,
      ao_max_request_date = ao_max_request_date,
      case_no = case_no
    )
  )
}
