# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions.

#' Get schedules schedule d sub id
#'
#' Schedule D, it shows debts and obligations owed to or by the committee that are required to be disclosed.
#'
#' @param sort_nulls_last (length-1 [base::logical()], optional) Toggle that sorts null values last
#' @param per_page (length-1 [base::list()], optional) The number of results returned per page. Defaults to 20.
#' @param sort_null_only (length-1 [base::logical()], optional) Toggle that filters out all rows having sort column that is non-null
#' @param sort_hide_null (length-1 [base::logical()], optional) Hide null values on sorted column(s).
#' @param sort (length-1 [base::character()], optional) Provide a field to sort by. Use `-` for descending order.
#' @param api_key (length-1 [base::character()]) API key for https://api.data.gov. Get one at https://api.data.gov/signup.
#' @param page (length-1 [base::list()], optional) For paginating through results, starting at page 1
#' @param sub_id (length-1 [base::character()])
#' @inheritParams .shared-params
#'
#' @returns `fec_get_schedules_schedule_d_sub_id()`: The API response.
#' @export
fec_get_schedules_schedule_d_sub_id <- function(
  sort_nulls_last,
  per_page,
  sort_null_only,
  sort_hide_null,
  sort,
  page,
  sub_id,
  api_key = Sys.getenv("FEC_API_KEY"),
  max_reqs = Inf,
  max_tries_per_req = 3
) {
  req <- req_fec_get_schedules_schedule_d_sub_id(
    sort_nulls_last = sort_nulls_last,
    per_page = per_page,
    sort_null_only = sort_null_only,
    sort_hide_null = sort_hide_null,
    sort = sort,
    page = page,
    sub_id = sub_id,
    api_key = api_key
  )
  resps <- nectar::req_perform_opinionated(
    req,
    max_reqs = max_reqs,
    max_tries_per_req = max_tries_per_req
  )
  return(nectar::resp_parse(resps))
}

#' @rdname fec_get_schedules_schedule_d_sub_id
#' @returns `req_fec_get_schedules_schedule_d_sub_id()`: A `httr2_request` request object.
req_fec_get_schedules_schedule_d_sub_id <- function(
  sort_nulls_last,
  per_page,
  sort_null_only,
  sort_hide_null,
  sort,
  page,
  sub_id,
  api_key = Sys.getenv("FEC_API_KEY")
) {
  fec_req_prepare(
    path = c("/schedules/schedule_d/{sub_id}/", sub_id = sub_id),
    method = "get",
    api_key = api_key,
    query = list(
      sort_nulls_last = sort_nulls_last,
      per_page = per_page,
      sort_null_only = sort_null_only,
      sort_hide_null = sort_hide_null,
      sort = sort,
      page = page
    )
  )
}
