# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions.

#' Get names audit candidates
#'
#' Search for candidates or committees by name. If you're looking for information on a particular person or group, using a name to find the `candidate_id` or `committee_id` on this endpoint can be a helpful first step.
#' 
#' @param api_key (length-1 \code{\link[base:character]{character}}) API key for https://api.data.gov. Get one at https://api.data.gov/signup.
#' @param q (length-1 \code{\link[base:list]{list}}) Name (candidate or committee) to search for
#' @inheritParams .shared-params
#'
#' @returns `fec_get_names_audit_candidates()`: The API response.
#' @export
fec_get_names_audit_candidates <- function(q, api_key = Sys.getenv("FEC_API_KEY"), max_reqs = Inf, max_tries_per_req = 3) {
  req <- req_fec_get_names_audit_candidates(q = q, api_key = api_key)
  resps <- nectar::req_perform_opinionated(
    req,
    max_reqs = max_reqs,
    max_tries_per_req = max_tries_per_req
  )
  return(nectar::resp_parse(resps))
}

#' @rdname fec_get_names_audit_candidates
#' @returns `req_fec_get_names_audit_candidates()`: A `httr2_request` request object.
req_fec_get_names_audit_candidates <- function(q, api_key = Sys.getenv("FEC_API_KEY")) {
  fec_req_prepare(
    path = "/names/audit_candidates/",
    method = "get",
    api_key = api_key,
    query = list(q = q)
  )
}
