# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions.

#' Get audit category
#'
#' This lists the options for the categories and subcategories available in the /audit-search/ endpoint.
#'
#' @param sort_nulls_last (length-1 \code{\link[base:logical]{logical}}, optional) Toggle that sorts null values last
#' @param page (length-1 \code{\link[base:list]{list}}, optional) For paginating through results, starting at page 1
#' @param primary_category_name (length-1 \code{\link[base:list]{list}}, optional) Primary Audit Category - No Findings or Issues/Not a Committee - Net Outstanding Campaign/Convention Expenditures/Obligations - Payments/Disgorgements - Allocation Issues - Prohibited Contributions - Disclosure - Recordkeeping - Repayment to US Treasury - Other - Misstatement of Financial Activity - Excessive Contributions - Failure to File Reports/Schedules/Notices - Loans - Referred Findings Not Listed
#' @param sort_hide_null (length-1 \code{\link[base:logical]{logical}}, optional) Hide null values on sorted column(s).
#' @param api_key (length-1 \code{\link[base:character]{character}}) API key for https://api.data.gov. Get one at https://api.data.gov/signup.
#' @param primary_category_id (length-1 \code{\link[base:list]{list}}, optional) Audit category ID (table PK)
#' @param sort_null_only (length-1 \code{\link[base:logical]{logical}}, optional) Toggle that filters out all rows having sort column that is non-null
#' @param per_page (length-1 \code{\link[base:list]{list}}, optional) The number of results returned per page. Defaults to 20.
#' @param sort (length-1 \code{\link[base:character]{character}}, optional) Provide a field to sort by. Use `-` for descending order.
#' @inheritParams .shared-params
#'
#' @returns `fec_get_audit_category()`: The API response.
#' @export
fec_get_audit_category <- function(
  sort_nulls_last,
  page,
  primary_category_name,
  sort_hide_null,
  primary_category_id,
  sort_null_only,
  per_page,
  sort,
  api_key = Sys.getenv("FEC_API_KEY"),
  max_reqs = Inf,
  max_tries_per_req = 3
) {
  req <- req_fec_get_audit_category(
    sort_nulls_last = sort_nulls_last,
    page = page,
    primary_category_name = primary_category_name,
    sort_hide_null = sort_hide_null,
    primary_category_id = primary_category_id,
    sort_null_only = sort_null_only,
    per_page = per_page,
    sort = sort,
    api_key = api_key
  )
  resps <- nectar::req_perform_opinionated(
    req,
    max_reqs = max_reqs,
    max_tries_per_req = max_tries_per_req
  )
  return(nectar::resp_parse(resps))
}

#' @rdname fec_get_audit_category
#' @returns `req_fec_get_audit_category()`: A `httr2_request` request object.
req_fec_get_audit_category <- function(
  sort_nulls_last,
  page,
  primary_category_name,
  sort_hide_null,
  primary_category_id,
  sort_null_only,
  per_page,
  sort,
  api_key = Sys.getenv("FEC_API_KEY")
) {
  fec_req_prepare(
    path = "/audit-category/",
    method = "get",
    api_key = api_key,
    query = list(
      sort_nulls_last = sort_nulls_last,
      page = page,
      primary_category_name = primary_category_name,
      sort_hide_null = sort_hide_null,
      primary_category_id = primary_category_id,
      sort_null_only = sort_null_only,
      per_page = per_page,
      sort = sort
    )
  )
}
