# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions.

#' Get schedules schedule d
#'
#' Schedule D, it shows debts and obligations owed to or by the committee that are required to be disclosed.
#'
#' @param creditor_debtor_name (length-1 `list`, optional)
#' @param max_image_number (length-1 `character`, optional) Maxium image number of the page where the schedule item is reported
#' @param sort_nulls_last (length-1 `logical`, optional) Toggle that sorts null values last
#' @param max_amount_outstanding_beginning (length-1 `double`, optional)
#' @param sort_hide_null (length-1 `logical`, optional) Hide null values on sorted column(s).
#' @param min_payment_period (length-1 `double`, optional)
#' @param max_amount_incurred (length-1 `double`, optional)
#' @param nature_of_debt (length-1 `character`, optional)
#' @param per_page (length-1 `list`, optional) The number of results returned per page. Defaults to 20.
#' @param max_amount_outstanding_close (length-1 `double`, optional)
#' @param candidate_id (length-1 `list`, optional) A unique identifier assigned to each candidate registered with the FEC. If a person runs for several offices, that person will have separate candidate IDs for each office.
#' @param page (length-1 `list`, optional) For paginating through results, starting at page 1
#' @param min_date (length-1 `Date`, optional) Minimum load date
#' @param committee_id (length-1 `list`, optional) A unique identifier assigned to each committee or filer registered with the FEC. In general committee id's begin with the letter C which is followed by eight digits.
#' @param min_amount_outstanding_close (length-1 `double`, optional)
#' @param api_key (length-1 `character`) API key for https://api.data.gov. Get one at https://api.data.gov/signup.
#' @param max_payment_period (length-1 `double`, optional)
#' @param min_image_number (length-1 `character`, optional) Minium image number of the page where the schedule item is reported
#' @param min_amount_incurred (length-1 `double`, optional)
#' @param sort_null_only (length-1 `logical`, optional) Toggle that filters out all rows having sort column that is non-null
#' @param image_number (length-1 `list`, optional) An unique identifier for each page where the electronic or paper filing is reported.
#' @param sort (length-1 `character`, optional) Provide a field to sort by. Use `-` for descending order.
#' @param min_amount_outstanding_beginning (length-1 `double`, optional)
#' @param max_date (length-1 `Date`, optional) Maximum load date
#' @inheritParams .shared-params
#'
#' @returns `fec_get_schedules_schedule_d()`: The API response.
#' @export
fec_get_schedules_schedule_d <- function(
  creditor_debtor_name,
  max_image_number,
  sort_nulls_last,
  max_amount_outstanding_beginning,
  sort_hide_null,
  min_payment_period,
  max_amount_incurred,
  nature_of_debt,
  per_page,
  max_amount_outstanding_close,
  candidate_id,
  page,
  min_date,
  committee_id,
  min_amount_outstanding_close,
  max_payment_period,
  min_image_number,
  min_amount_incurred,
  sort_null_only,
  image_number,
  sort,
  min_amount_outstanding_beginning,
  max_date,
  api_key = Sys.getenv("FEC_API_KEY"),
  max_reqs = Inf,
  max_tries_per_req = 3
) {
  req <- req_fec_get_schedules_schedule_d(
    creditor_debtor_name = creditor_debtor_name,
    max_image_number = max_image_number,
    sort_nulls_last = sort_nulls_last,
    max_amount_outstanding_beginning = max_amount_outstanding_beginning,
    sort_hide_null = sort_hide_null,
    min_payment_period = min_payment_period,
    max_amount_incurred = max_amount_incurred,
    nature_of_debt = nature_of_debt,
    per_page = per_page,
    max_amount_outstanding_close = max_amount_outstanding_close,
    candidate_id = candidate_id,
    page = page,
    min_date = min_date,
    committee_id = committee_id,
    min_amount_outstanding_close = min_amount_outstanding_close,
    max_payment_period = max_payment_period,
    min_image_number = min_image_number,
    min_amount_incurred = min_amount_incurred,
    sort_null_only = sort_null_only,
    image_number = image_number,
    sort = sort,
    min_amount_outstanding_beginning = min_amount_outstanding_beginning,
    max_date = max_date,
    api_key = api_key
  )
  resps <- nectar::req_perform_opinionated(
    req,
    max_reqs = max_reqs,
    max_tries_per_req = max_tries_per_req
  )
  return(nectar::resp_parse(resps))
}

#' @rdname fec_get_schedules_schedule_d
#' @returns `req_fec_get_schedules_schedule_d()`: (`httr2_request`) A [httr2::request()] object.
req_fec_get_schedules_schedule_d <- function(
  creditor_debtor_name,
  max_image_number,
  sort_nulls_last,
  max_amount_outstanding_beginning,
  sort_hide_null,
  min_payment_period,
  max_amount_incurred,
  nature_of_debt,
  per_page,
  max_amount_outstanding_close,
  candidate_id,
  page,
  min_date,
  committee_id,
  min_amount_outstanding_close,
  max_payment_period,
  min_image_number,
  min_amount_incurred,
  sort_null_only,
  image_number,
  sort,
  min_amount_outstanding_beginning,
  max_date,
  api_key = Sys.getenv("FEC_API_KEY")
) {
  fec_req_prepare(
    path = "/schedules/schedule_d/",
    method = "get",
    api_key = api_key,
    query = list(
      creditor_debtor_name = creditor_debtor_name,
      max_image_number = max_image_number,
      sort_nulls_last = sort_nulls_last,
      max_amount_outstanding_beginning = max_amount_outstanding_beginning,
      sort_hide_null = sort_hide_null,
      min_payment_period = min_payment_period,
      max_amount_incurred = max_amount_incurred,
      nature_of_debt = nature_of_debt,
      per_page = per_page,
      max_amount_outstanding_close = max_amount_outstanding_close,
      candidate_id = candidate_id,
      page = page,
      min_date = min_date,
      committee_id = committee_id,
      min_amount_outstanding_close = min_amount_outstanding_close,
      max_payment_period = max_payment_period,
      min_image_number = min_image_number,
      min_amount_incurred = min_amount_incurred,
      sort_null_only = sort_null_only,
      image_number = image_number,
      sort = sort,
      min_amount_outstanding_beginning = min_amount_outstanding_beginning,
      max_date = max_date
    )
  )
}
