# These tests were generated by the {beekeeper} package, based on the paths
# element from the source API description. You will likely need to supply
# arguments for the tests to succeed. We recommend expanding these tests to
# check for specific expectations, rather than simply using a snapshot.

with_mock_dir("api/path/apis/get_providers", {
  test_that("get_providers() returns expected result", {
    beekeeper::skip_if_not_exported("get_providers")
    expect_snapshot({
      test_result <- get_providers()
      test_result
    })
  })

})
