# These tests were generated by the {beekeeper} package, based on the paths
# element from the source API description. You will likely need to supply
# arguments for the tests to succeed. We recommend expanding these tests to
# check for specific expectations, rather than simply using a snapshot.

httptest2::with_mock_dir("api/path/apis/list_apis", {
  test_that("list_apis() returns expected result", {
    beekeeper::skip_if_not_exported("list_apis")
    expect_snapshot({
      test_result <- list_apis()
      test_result
    })
  })

})
