# These tests were generated by the {beekeeper} package, based on the paths
# element from the source API description. You will likely need to supply
# arguments for the tests to succeed. We recommend expanding these tests to
# check for specific expectations, rather than simply using a snapshot.

with_mock_dir("api/path/apis/get_metrics", {
  test_that("get_metrics() returns expected result", {
    beekeeper::skip_if_not_exported("get_metrics")
    expect_snapshot({
      test_result <- get_metrics()
      test_result
    })
  })

})
