# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions.

#' Get basic metrics
#'
#' Some basic metrics for the entire directory. Just stunning numbers to put on a front page and are intended purely for WoW effect :)
#'
#'
#'
#' @returns `guru_get_metrics()`: The API response.
#' @export
guru_get_metrics <- function(max_reqs = Inf, max_tries_per_req = 3) {
  req <- req_guru_get_metrics()
  resps <- nectar::req_perform_opinionated(
    req,
    max_reqs = max_reqs,
    max_tries_per_req = max_tries_per_req
  )
  return(nectar::resp_parse(resps))
}

#' @rdname guru_get_metrics
#' @returns `req_guru_get_metrics()`: A `httr2_request` request object.
req_guru_get_metrics <- function() {
  guru_req_prepare(
    path = "/metrics.json",
    method = "get"
  )
}
