# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions.

#' List all serviceNames for a particular provider
#'
#' List all serviceNames in the directory for a particular providerName
#' 
#' @param provider (length-1 \code{\link[base:character]{character}}) 
#' @inheritParams .shared-params
#'
#' @returns `guru_get_services()`: The API response.
#' @export
guru_get_services <- function(provider, max_reqs = Inf, max_tries_per_req = 3) {
  req <- req_guru_get_services(provider = provider)
  resps <- nectar::req_perform_opinionated(
    req,
    max_reqs = max_reqs,
    max_tries_per_req = max_tries_per_req
  )
  return(nectar::resp_parse(resps))
}

#' @rdname guru_get_services
#' @returns `req_guru_get_services()`: A `httr2_request` request object.
req_guru_get_services <- function(provider) {
  guru_req_prepare(
    path = c("/{provider}/services.json", provider = provider),
    method = "get"
  )
}
