# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions.

#' List all APIs for a particular provider
#'
#' List all APIs in the directory for a particular providerName Returns links to the individual API entry for each API.
#'
#'
#' @param provider (length-1 \code{\link[base:character]{character}})
#'
#' @returns `guru_get_provider()`: The API response.
#' @export
guru_get_provider <- function(provider, max_reqs = Inf, max_tries_per_req = 3) {
  req <- req_guru_get_provider(provider = provider)
  resps <- nectar::req_perform_opinionated(
    req,
    max_reqs = max_reqs,
    max_tries_per_req = max_tries_per_req
  )
  return(nectar::resp_parse(resps))
}

#' @rdname guru_get_provider
#' @returns `req_guru_get_provider()`: A `httr2_request` request object.
req_guru_get_provider <- function(provider) {
  guru_req_prepare(
    path = c("/{provider}.json", provider = provider),
    method = "get"
  )
}
