# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions.

#' Retrieve one version of a particular API with a serviceName.
#'
#' Returns the API entry for one specific version of an API where there is a serviceName.
#'
#' @param provider (length-1 \code{\link[base:character]{character}})
#' @param service (length-1 \code{\link[base:character]{character}})
#' @param api (length-1 \code{\link[base:character]{character}})
#' @inheritParams .shared-params
#'
#' @returns `guru_get_service_api()`: The API response.
#' @export
guru_get_service_api <- function(provider, service, api, max_reqs = Inf, max_tries_per_req = 3) {
  req <- req_guru_get_service_api(provider = provider, service = service, api = api)
  resps <- nectar::req_perform_opinionated(
    req,
    max_reqs = max_reqs,
    max_tries_per_req = max_tries_per_req
  )
  return(nectar::resp_parse(resps))
}

#' @rdname guru_get_service_api
#' @returns `req_guru_get_service_api()`: A `httr2_request` request object.
req_guru_get_service_api <- function(provider, service, api) {
  guru_req_prepare(
    path = c("/specs/{provider}/{service}/{api}.json", provider = provider, service = service, api = api),
    method = "get"
  )
}
