# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions.

#' List all providers
#'
#' List all the providers in the directory
#' 
#' @inheritParams .shared-params
#'
#' @returns `guru_get_providers()`: The API response.
#' @export
guru_get_providers <- function(max_reqs = Inf, max_tries_per_req = 3) {
  req <- req_guru_get_providers()
  resps <- nectar::req_perform_opinionated(
    req,
    max_reqs = max_reqs,
    max_tries_per_req = max_tries_per_req
  )
  return(nectar::resp_parse(resps))
}

#' @rdname guru_get_providers
#' @returns `req_guru_get_providers()`: A `httr2_request` request object.
req_guru_get_providers <- function() {
  guru_req_prepare(
    path = "/providers.json",
    method = "get"
  )
}
