# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions.

#' addBoards()
#'
#' addBoards()
#' 
#' @param key (length-1 `character`) <a href="https://trello.com/1/appKey/generate" target="_blank">Generate your application key</a>
#' @param token (length-1 `character`) <a href="https://trello.com/docs/gettingstarted/index.html#getting-a-token-from-a-user" target="_blank">Getting a token from a user</a>
#' @inheritParams .shared-params
#'
#' @returns `add_boards()`: The API response.
#' @keywords internal
add_boards <- function(key = Sys.getenv("TRELLO_KEY"),
token = Sys.getenv("TRELLO_TOKEN"), max_reqs = Inf, max_tries_per_req = 3) {
  req <- req_add_boards(key = key, token = token)
  resps <- nectar::req_perform_opinionated(
    req,
    max_reqs = max_reqs,
    max_tries_per_req = max_tries_per_req
  )
  return(nectar::resp_parse(resps))
}

#' @rdname add_boards
#' @returns `req_add_boards()`: (`httr2_request`) A [httr2::request()] object.
#' @export
req_add_boards <- function(key = Sys.getenv("TRELLO_KEY"),
token = Sys.getenv("TRELLO_TOKEN")) {
  trello_req_prepare(
    path = "/boards",
    method = "post",
    key = key, token = token,
    tidy_policy = tidy_policy_add_boards()
  )
}

#' @rdname add_boards
#' @returns `tidy_policy_add_boards()`: (`nectar_tidy_policy`) 
#'   A list like the ones returned by [nectar::tidy_policy_prepare()].
#' @export
tidy_policy_add_boards <- function() {
  nectar::tidy_policy_body_auto()
}
