# These functions were generated by the {beekeeper} package, based on developer
# inputs. You may need to manually rename these functions or tweak their
# arguments.
#
# {beekeeper} currently only supports JSON response bodies with cursor
# pagination.

{{#pagination_schemes}}
#' Apply pagination
#'
#' Process a `resp` object to determine how and whether to continue iteration,
#' then build the next `req`. Use as the `pagination_fn` argument to
#' [{{api_abbr}}_req_prepare()].
#'
#' @inheritParams .shared-params
#' @inherit nectar::req_prepare return
#' @keywords internal
{{api_abbr}}_pagination_{{family}} <- function(resp, req) {
  nectar::iterate_with_json_cursor(
    "{{param_name}}"{{#next_cursor_path}},
    c({{{.}}}){{/next_cursor_path}}
  )(resp, req)
}

{{/pagination_schemes}}
