# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions.

#' {{operation_summary}}
#'
#' {{operation_description}}
#' {{#params}}
#' @param {{name}} ({{{class}}}) {{{description}}}{{/params}}
#' @inheritParams .shared-params
#'
#' @returns `{{fn_prefix}}{{operation_id}}()`: The API response.
#' @export
{{fn_prefix}}{{operation_id}} <- function({{#args}}{{{args}}}, {{/args}}{{#has_security}}{{{security_signature}}}, {{/has_security}}max_reqs = Inf, max_tries_per_req = 3) {
  req <- req_{{fn_prefix}}{{operation_id}}({{#args_named}}{{{args_named}}}{{/args_named}}{{#has_security}}{{#args_named}}, {{/args_named}}{{{security_arg_list}}}{{/has_security}})
  resps <- nectar::req_perform_opinionated(
    req,
    max_reqs = max_reqs,
    max_tries_per_req = max_tries_per_req
  )
  return(nectar::resp_parse(resps))
}

#' @rdname {{fn_prefix}}{{operation_id}}
#' @returns `req_{{fn_prefix}}{{operation_id}}()`: (`httr2_request`) A [httr2::request()] object.
req_{{fn_prefix}}{{operation_id}} <- function({{#args}}{{{args}}}{{/args}}{{#has_security}}{{#args}}, {{/args}}{{{security_signature}}}{{/has_security}}) {
{{#validations}}
  {{name}} <- stbl::{{to_r}}({{name}})
{{/validations}}
  {{api_abbr}}_req_prepare(
    path = {{{path}}},
    method = "{{method}}"{{#has_security}},
    {{security_arg_list}}{{/has_security}}{{#params_query}},
    query = list({{params_query}}){{/params_query}}{{#params_header}},
    header = list({{params_header}}){{/params_header}}{{#params_cookie}},
    cookie = list({{params_cookie}}){{/params_cookie}}{{#pagination}},
    pagination_fn = {{pagination_fn}}{{/pagination}},
    tidy_policy = tidy_policy_{{fn_prefix}}{{operation_id}}()
  )
}

tidy_policy_{{fn_prefix}}{{operation_id}} <- function() {
  {{{tidy_policy_body}}}
}
