# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions.

#' {{summary}}
#'
#' {{description}}
#' {{#params}}
#' @param {{name}} ({{{class}}}) {{{description}}}{{/params}}
#' @inheritParams .shared-params
#'
#' @returns `{{api_abbr}}_{{operation_id}}()`: The API response.
#' @export
{{api_abbr}}_{{operation_id}} <- function({{#args}}{{{args}}}, {{/args}}{{#has_security}}{{{security_signature}}}, {{/has_security}}max_reqs = Inf, max_tries_per_req = 3) {
  req <- req_{{api_abbr}}_{{operation_id}}({{#args_named}}{{{args_named}}}{{/args_named}}{{#has_security}}{{#args_named}}, {{/args_named}}{{{security_arg_list}}}{{/has_security}})
  resps <- nectar::req_perform_opinionated(
    req,
    max_reqs = max_reqs,
    max_tries_per_req = max_tries_per_req
  )
  return(nectar::resp_parse(resps))
}

#' @rdname {{api_abbr}}_{{operation_id}}
#' @returns `req_{{api_abbr}}_{{operation_id}}()`: A `httr2_request` request object.
req_{{api_abbr}}_{{operation_id}} <- function({{#args}}{{{args}}}{{/args}}{{#has_security}}{{#args}}, {{/args}}{{{security_signature}}}{{/has_security}}) {
  {{api_abbr}}_req_prepare(
    path = {{{path}}},
    method = "{{method}}"{{#has_security}},
    {{security_arg_list}}{{/has_security}}{{#params_query}},
    query = list({{params_query}}){{/params_query}}{{#params_header}},
    header = list({{params_header}}){{/params_header}}{{#params_cookie}},
    cookie = list({{params_cookie}}){{/params_cookie}}{{#pagination}},
    pagination_fn = {{pagination_fn}}{{/pagination}}{{#tidy}},
    tidy_policy = {{tidy_policy}}{{/tidy}}
  )
}
