# These functions were generated by the {beekeeper} package, based on the paths
# element from the source API description. You should carefully review these
# functions.

#' {{summary}}
#'
#' {{description}}
#'{{#has_security}}
#' @inheritParams .shared-params{{/has_security}}
#' {{#params}}
#' @param {{name}} ({{{class}}}) {{{description}}}{{/params}}
#'
#' @returns `{{operation_id}}()`: The API response.
#' @export
{{operation_id}} <- function({{{args}}}{{#has_security}}{{#args}},{{/args}}{{{security_signature}}}{{/has_security}}) {
  req <- req_{{operation_id}}(
    # TODO: Add params when I have an example that has params
  )
  resps <- nectar::req_perform_opinionated(
    req,
    max_reqs = max_reqs, # Should only include this with pagination.
    max_tries_per_req = max_tries_per_req
  )
  return(nectar::resp_tidy(resps))
}

#' @rdname {{operation_id}}
#' @returns `req_{{operation_id}}()`: A `httr2_request` request object.
req_{{operation_id}} <- function({{{args}}}{{#has_security}}{{#args}},{{/args}}{{{security_signature}}}{{/has_security}}) {
  slack_req_prepare(
    path = "{{{path}}}",
    method = "{{method}}"{{#has_security}},
    {{security_arg_list}}{{/has_security}}{{#params_query}},
    query = list({{params_query}}){{/params_query}}{{#params_header}},
    body = list({{params_header}}){{/params_header}}{{#pagination}},
    pagination_fn = {{pagination_fn}}{{/pagination}}{{#tidy}},
    tidy_fn = {{tidy_fn}}{{/tidy}}
  )
}
