# These tests were generated by the {beekeeper} package, based on the paths
# element from the source API description. You will likely need to supply
# arguments for the tests to succeed. We recommend expanding these tests to
# check for specific expectations, rather than simply using a snapshot.

with_mock_dir("api/path/{{tag}}", {
{{#paths}}
  test_that("{{fn_prefix}}{{operation_id}}() returns expected result", {
    expect_snapshot({
      test_result <- {{fn_prefix}}{{operation_id}}({{{test_args}}})
      test_result
    })
  })

{{/paths}}

})
