#' Use a beekeeper config file to generate code
#'
#' Creates or updates package files based on the information in a beekeeper
#' config file (generated by [use_beekeeper()] or manually). The files enforce
#' an opinionated framework for API packages.
#'
#' @inheritParams .shared-params
#'
#' @returns (`character`, invisibly) Paths to files that were added or updated.
#' @export
generate_pkg <- function(
  api_abbr = read_api_abbr(pkg_dir, config_filename),
  api_definition = read_api_definition(
    pkg_dir,
    read_rapid_filename(pkg_dir, config_filename)
  ),
  api_title = read_api_title(pkg_dir, config_filename),
  config_filename = "_beekeeper.yml",
  pkg_dir = "."
) {
  # TODO: Confirm that they use github & everything is committed. Error or warn
  # if not, letting them know that this can be destructive. Skip this check in
  # tests.
  .assert_is_pkg(pkg_dir)
  api_abbr <- stbl::stabilize_chr_scalar(api_abbr)
  api_title <- stbl::stabilize_chr_scalar(api_title)
  save_security_data <- fs::file_exists(fs::path(pkg_dir, config_filename))
  security_data <- generate_pkg_auth(
    api_abbr = api_abbr,
    security_schemes = api_definition@components@security_schemes,
    save_security_data = save_security_data,
    config_filename = config_filename,
    pkg_dir = pkg_dir
  )
  shared_file_path <- generate_pkg_shared_params(
    security_data = security_data,
    pkg_dir = pkg_dir
  )
  prep_files <- generate_pkg_req_prepare(
    api_abbr = api_abbr,
    api_definition = api_definition,
    api_title = api_title,
    security_data = security_data,
    pkg_dir = pkg_dir
  )
  path_files <- generate_pkg_paths(
    api_abbr = api_abbr,
    api_definition = api_definition,
    security_data = security_data,
    pkg_dir = pkg_dir
  )
  touched_files <- c(
    shared_file_path,
    prep_files,
    security_data$security_file_path,
    path_files
  )
  return(invisible(touched_files))
}
