#' Use a beekeeper config file to generate code
#'
#' Creates or updates package files based on the information in a beekeeper
#' config file (generated by [use_beekeeper()] or manually). The files enforce
#' an opinionated framework for API packages.
#'
#' @inheritParams .shared-params
#'
#' @return A character vector of paths to files that were added or updated,
#'   invisibly.
#' @export
generate_pkg <- function(
  api_abbr = NULL,
  api_definition = NULL,
  api_title = NULL,
  config_file = "_beekeeper.yml",
  pkg_dir = "."
) {
  # TODO: Confirm that they use github & everything is committed. Error or warn
  # if not, letting them know that this can be destructive. Skip this check in
  # tests.
  .assert_is_pkg(pkg_dir)
  if (
    is.null(api_abbr) ||
      is.null(api_definition) ||
      is.null(api_title)
  ) {
    config <- read_config(pkg_dir = pkg_dir, config_file = config_file)
  }
  if (is.null(api_abbr)) {
    api_abbr <- config$api_abbr
  } else {
    api_abbr <- stbl::stabilize_character_scalar(api_abbr)
  }
  if (is.null(api_title)) {
    api_title <- config$api_title
  } else {
    api_title <- stbl::stabilize_character_scalar(api_title)
  }
  if (is.null(api_definition)) {
    api_definition <- read_api_definition(
      pkg_dir = pkg_dir,
      rapid_file = config$rapid_file
    )
  }
  config <- list(api_abbr = api_abbr, api_title = api_title)
  security_data <- .generate_security(
    api_abbr,
    api_definition@components@security_schemes
  )
  security_arg_names <- security_data$security_arg_names %|0|% character()
  .setup_r(
    pkg_dir,
    include_stbl = .paths_need_stbl(
      api_definition@paths,
      security_arg_names
    )
  )
  touched_files <- .generate_pkg_impl(config, api_definition, security_data)
  return(invisible(touched_files))
}

.generate_pkg_impl <- function(config, api_definition, security_data) {
  prep_files <- .generate_prepare(config, api_definition, security_data)
  pagination_data <- .generate_pagination()
  path_files <- .generate_paths(
    paths = api_definition@paths,
    api_abbr = config$api_abbr,
    security_data = security_data,
    pagination_data = pagination_data,
    base_url = api_definition@servers@url
  )
  shared_file_path <- .generate_shared_params(security_data)
  touched_files <- c(
    shared_file_path,
    prep_files,
    security_data$security_file_path,
    pagination_data$pagination_file_path,
    path_files
  )
  return(invisible(touched_files))
}
