#' Use a beekeeper config file to generate code
#'
#' Creates or updates package files based on the information in a beekeeper
#' config file (generated by [use_beekeeper()] or manually). The files enforce
#' an opinionated framework for API packages.
#'
#' @param config_file (`length-1 character` or `fs_path`) The path to a
#'   beekeeper yaml file. All package files are created relative to this file.
#' @param pkg_dir (`length-1 character` or `fs_path`) The directory in which the
#'   package files will be created. Defaults to the directory of the config
#'   file.
#'
#' @return A character vector of paths to files that were added or updated,
#'   invisibly.
#' @export
generate_pkg <- function(
  config_file = "_beekeeper.yml",
  pkg_dir = fs::path_dir(config_file)
) {
  # TODO: Confirm that they use github & everything is committed. Error or warn
  # if not, letting them know that this can be destructive. Skip this check in
  # tests.
  .assert_is_pkg(pkg_dir)
  config <- .read_config(config_file)
  api_definition <- .read_api_definition(pkg_dir, config$rapid_file)
  .setup_r(pkg_dir)
  touched_files <- .generate_pkg_impl(config, api_definition)
  return(invisible(touched_files))
}

.generate_pkg_impl <- function(config, api_definition) {
  security_data <- .generate_security(
    config$api_abbr,
    api_definition@components@security_schemes
  )
  prep_files <- .generate_prepare(config, api_definition, security_data)
  pagination_data <- .generate_pagination()
  path_files <- .generate_paths(
    paths = api_definition@paths,
    api_abbr = config$api_abbr,
    security_data = security_data,
    pagination_data = pagination_data,
    base_url = api_definition@servers@url
  )
  shared_file_path <- .generate_shared_params(security_data)
  touched_files <- c(
    shared_file_path,
    prep_files,
    security_data$security_file_path,
    pagination_data$pagination_file_path,
    path_files
  )
  return(invisible(touched_files))
}
