#' Read a beekeeper config file
#'
#' Read a YAML file (default name `_beekeeper.yml`) with configuration
#' information about the API and the package. This file is generated by
#' [use_beekeeper()], or can be created manually.
#'
#' The configuration information must contain these fields:
#'
#' - `api_title` (`character(1)`): The title of the API, used in documentation
#' and messages.
#' - `api_abbr` (`character(1)`): An abbreviation for the API, used in function
#' names and other identifiers.
#' - `api_version` (`character(1)`): The version of the API.
#' - `rapid_filename` (`character(1)`): The name of the file (relative to the
#' package root) where the API definition is stored as an RDS file. By default,
#' this is `_beekeeper_rapid.rds`, and is generated by [use_beekeeper()] based
#' on an OpenAPI definition file.
#' - `updated_on` (`character(1)`): A timestamp of when the API definition was
#' last updated, in the format "YYYY-MM-DD HH:MM:SS" (UTC).
#' - `security_data_filename` (`character(1)`): Optionally, the path (relative
#' to the package root) where generated security metadata is stored.
#'
#' @inheritParams .shared-params
#' @returns (`list`) Configuration information, with elements `api_title`,
#'   `api_abbr`, `api_version`, `rapid_filename`, and `updated_on`, plus
#'   `security_data_filename` when present.
#' @export
#' @family config readers
#' @examples
#' read_config(pkg_dir = fs::path_package("beekeeper", "guru"))
read_config <- function(pkg_dir = ".", config_filename = "_beekeeper.yml") {
  config <- yaml::read_yaml(fs::path(pkg_dir, config_filename))
  return(.stabilize_config(config))
}

#' Stabilize beekeeper config values
#'
#' @inheritParams .shared-params
#' @returns (`list`) A stabilized config list.
#' @keywords internal
.stabilize_config <- function(config) {
  config$api_title <- stbl::stabilize_chr_scalar(config$api_title)
  config$api_abbr <- stbl::stabilize_chr_scalar(config$api_abbr)
  config$api_version <- stbl::stabilize_chr_scalar(
    config$api_version,
    allow_null = TRUE
  )
  config$rapid_filename <- stbl::stabilize_chr_scalar(config$rapid_filename)
  config$updated_on <- config$updated_on %&&%
    strptime(
      config$updated_on,
      format = "%Y-%m-%d %H:%M:%S",
      tz = "UTC"
    )
  if ("security_data_filename" %in% names(config)) {
    config$security_data_filename <- stbl::stabilize_chr_scalar(
      config$security_data_filename
    )
  }
  return(config)
}

.read_config_field <- function(
  field,
  pkg_dir,
  config_filename,
  default = NULL
) {
  pkg_dir <- fs::path_abs(pkg_dir)
  config <- read_config(pkg_dir, config_filename)
  if (field %in% names(config)) {
    return(config[[field]])
  }
  default
}

#' Read rapid_filename config field
#'
#' Read the `rapid_filename` field from a beekeeper config file.
#'
#' @inheritParams .shared-params
#'
#' @returns (`character(1)`) The `rapid_filename` field from the beekeeper
#'   config file.
#' @export
#' @family config readers
#' @examples
#' read_rapid_filename(pkg_dir = fs::path_package("beekeeper", "guru"))
read_rapid_filename <- function(
  pkg_dir = ".",
  config_filename = "_beekeeper.yml"
) {
  .read_config_field("rapid_filename", pkg_dir, config_filename)
}

#' Read api_abbr config field
#'
#' Read the `api_abbr` field from a beekeeper config file.
#'
#' @inheritParams .shared-params
#'
#' @returns (`character(1)`) The `api_abbr` field from the beekeeper
#'   config file.
#' @export
#' @family config readers
#' @examples
#' read_api_abbr(pkg_dir = fs::path_package("beekeeper", "guru"))
read_api_abbr <- function(pkg_dir = ".", config_filename = "_beekeeper.yml") {
  .read_config_field("api_abbr", pkg_dir, config_filename)
}

#' Read api_title config field
#'
#' Read the `api_title` field from a beekeeper config file.
#'
#' @inheritParams .shared-params
#'
#' @returns (`character(1)`) The `api_title` field from the beekeeper
#'   config file.
#' @export
#' @family config readers
#' @examples
#' read_api_title(pkg_dir = fs::path_package("beekeeper", "guru"))
read_api_title <- function(pkg_dir = ".", config_filename = "_beekeeper.yml") {
  .read_config_field("api_title", pkg_dir, config_filename)
}

#' Read saved security metadata filename
#'
#' Read the `security_data_filename` field from a beekeeper config file.
#'
#' @inheritParams .shared-params
#'
#' @returns (`character(1)`) The configured security metadata file path.
#' @export
#' @family config readers
#' @examples
#' read_security_data_filename(
#'   pkg_dir = fs::path_package("beekeeper", "trello")
#' )
read_security_data_filename <- function(
  pkg_dir = ".",
  config_filename = "_beekeeper.yml"
) {
  .read_config_field(
    "security_data_filename",
    pkg_dir,
    config_filename,
    default = "_beekeeper_security.yml"
  )
}

#' Read an API definition file
#'
#' Read an RDS file (default name `_beekeeper_rapid.rds`) with the API
#' definition stored as a [rapid::class_rapid()] object. This file is generated
#' by [use_beekeeper()] based on an OpenAPI definition file.
#'
#' @inheritParams .shared-params
#' @returns (`rapid::class_rapid`) The definition of the API.
#' @export
#' @family config readers
#' @examples
#' api_definition <- read_api_definition(fs::path_package("beekeeper", "guru"))
#' class(api_definition)
#' api_definition@info@origin@url
read_api_definition <- function(
  pkg_dir = ".",
  rapid_filename = read_rapid_filename(pkg_dir)
) {
  pkg_dir <- fs::path_abs(pkg_dir)
  readRDS(fs::path(pkg_dir, rapid_filename))
}

#' Read security schemes from an API definition
#'
#' Read the security schemes from an API definition stored as a
#' [rapid::class_rapid()] object.
#'
#' @inheritParams .shared-params
#' @returns (`rapid::class_security_schemes`) Security schemes from the API
#'   definition.
#' @export
#' @family config readers
read_security_schemes <- function(
  pkg_dir = ".",
  rapid_filename = read_rapid_filename(pkg_dir)
) {
  read_api_definition(pkg_dir, rapid_filename)@components@security_schemes
}

#' Read saved security metadata
#'
#' Read prepared security metadata from a YAML file (default name
#' `_beekeeper_security.yml`) generated via [generate_pkg_auth()].
#'
#' @inheritParams .shared-params
#' @returns (`list`) Saved security metadata.
#' @export
#' @family config readers
#' @examples
#' read_security_data(pkg_dir = fs::path_package("beekeeper", "trello"))
read_security_data <- function(
  pkg_dir = ".",
  config_filename = "_beekeeper.yml",
  security_data_filename = read_security_data_filename(
    pkg_dir,
    config_filename
  )
) {
  pkg_dir <- fs::path_abs(pkg_dir)
  security_path <- fs::path(pkg_dir, security_data_filename)
  if (!fs::file_exists(security_path)) {
    return(list())
  }
  security_data <- yaml::read_yaml(fs::path(pkg_dir, security_data_filename))
  if (is.null(security_data)) {
    return(list())
  }
  security_data
}
