#' Configure a package to use beekeeper
#'
#' Create a configuration file for a package to use beekeeper. The configuration
#' file tracks information that will be used for generation of other functions,
#' and the timestamp when the configuration was last updated or used.
#'
#' @inheritParams rlang::args_dots_empty
#' @param x An object to use to define the configuration. It must be
#'   translatable to a [rapid::class_rapid()] object by [rapid::as_rapid()].
#'   Usually this will be a url pointing to an OpenAPI document, or a list
#'   generated by reading such a document.
#' @inheritParams .shared-params
#'
#' @returns (`character(1)`, invisibly) The path to the configuration file. The
#'   config file is written as a side effect of this function. The rapid object
#'   is also written, and the path to that file (relative to `pkg_dir`) is saved
#'   in the config file.
#' @export
#' @examplesIf rlang::is_installed("withr")
#' # Set up an empty package.
#' pkg_dir <- unclass(fs::path_norm(withr::local_tempdir()))
#' usethis::create_package(pkg_dir, open = FALSE, check_name = FALSE)
#' usethis::local_project(pkg_dir)
#'
#' # Read an api definition. This could also simply be a URL to such a
#' # definition.
#' api_definition <- read_api_definition(fs::path_package("beekeeper", "guru"))
#'
#' # Set up the package to use beekeeper with that definition.
#' use_beekeeper(api_definition, "guru")
#' read_config()
#' all.equal(read_api_definition(), api_definition)
#'
#' # Clean up.
#' withr::deferred_run()
use_beekeeper <- function(
  x,
  api_abbr,
  ...,
  pkg_dir = ".",
  config_filename = "_beekeeper.yml",
  rapid_filename = "_beekeeper_rapid.rds"
) {
  rlang::check_dots_empty()
  .assert_is_pkg(pkg_dir)
  api_definition <- rapid::as_rapid(x)
  rapid_filename <- .write_rapid(api_definition, rapid_filename, pkg_dir)
  config_filename <- .write_config(
    api_definition,
    api_abbr,
    rapid_filename,
    config_filename,
    pkg_dir
  )

  return(invisible(fs::path(pkg_dir, config_filename)))
}

#' Assert the beekeeper config file exists
#'
#' @inheritParams .shared-params
#' @returns (`NULL`, invisibly) Called for side effect of asserting the config
#'   file exists.
#' @keywords internal
.assert_config_exists <- function(
  pkg_dir,
  config_filename,
  call = caller_env()
) {
  config_path <- fs::path_abs(fs::path(pkg_dir, config_filename))
  if (!fs::file_exists(config_path)) {
    .pkg_abort(
      c(
        "No beekeeper configuration found.",
        i = "Expected to find a config file at {.code {config_path}}.",
        i = "Use {.fn beekeeper::use_beekeeper} to create a configuration."
      ),
      c("setup", "missing_config"),
      call = call
    )
  }
}

#' Write the rapid definition file
#'
#' @inheritParams .shared-params
#' @returns (`character(1)`) The written file path.
#' @keywords internal
.write_rapid <- function(api_definition, rapid_filename, pkg_dir) {
  rapid_filename <- stbl::stabilize_chr_scalar(rapid_filename)
  saveRDS(api_definition, fs::path(pkg_dir, rapid_filename))
  usethis::with_project(pkg_dir, usethis::use_build_ignore(rapid_filename))
  return(rapid_filename)
}

#' Write the beekeeper config file
#'
#' @inheritParams .shared-params
#' @returns (`character(1)`) The written config file path.
#' @keywords internal
.write_config <- function(
  api_definition,
  api_abbr,
  rapid_filename,
  config_filename,
  pkg_dir
) {
  config_filename <- stbl::stabilize_chr_scalar(config_filename)
  update_time <- strptime(Sys.time(), format = "%Y-%m-%d %H:%M:%S", tz = "UTC")
  config <- list(
    api_title = api_definition@info@title,
    api_abbr = stbl::stabilize_chr_scalar(api_abbr),
    api_version = api_definition@info@version,
    rapid_filename = rapid_filename,
    updated_on = as.character(update_time)
  )
  config_origin <- .config_origin(api_definition)
  if (!is.null(config_origin)) {
    config$api_definition_origin <- config_origin
  }
  yaml::write_yaml(config, file = fs::path(pkg_dir, config_filename))
  memoise::forget(read_config)
  usethis::with_project(pkg_dir, usethis::use_build_ignore(config_filename))
  return(config_filename)
}

.config_origin <- function(api_definition) {
  origin <- api_definition@info@origin
  config_origin <- Filter(
    Negate(is.null),
    list(
      url = .optional_origin_field(origin@url),
      format = .optional_origin_field(origin@format),
      version = .optional_origin_field(origin@version)
    )
  )
  if (!length(config_origin)) {
    return(NULL)
  }
  config_origin
}

.optional_origin_field <- function(field) {
  if (!is.character(field) || !length(field) || !nzchar(field[[1]])) {
    return(NULL)
  }
  field[[1]]
}

#' Update one config field
#'
#' @inheritParams .shared-params
#' @param field (`character(1)`) The config field to write.
#' @param value (`character(1)`) The value to write.
#' @returns (`character(1)`) The written config filename.
#' @keywords internal
.write_config_field <- function(field, value, config_filename, pkg_dir) {
  .assert_config_exists(pkg_dir, config_filename)
  config <- yaml::read_yaml(fs::path(pkg_dir, config_filename))
  config[[field]] <- value
  yaml::write_yaml(config, file = fs::path(pkg_dir, config_filename))
  memoise::forget(read_config)
  usethis::with_project(pkg_dir, usethis::use_build_ignore(config_filename))
  return(config_filename)
}
