#' Configure a package to use beekeeper
#'
#' Create a configuration file for a package to use beekeeper. The configuration
#' file tracks information that will be used for generation of other functions,
#' and the timestamp when the configuration was last updated or used.
#'
#' @inheritParams rlang::args_dots_empty
#' @param x An object to use to define the configuration. It must be
#'   translatable to a [rapid::class_rapid()] object by [rapid::as_rapid()].
#'   Usually this will be a url pointing to an OpenAPI document, or a list
#'   generated by reading such a document.
#' @inheritParams .shared-params
#'
#' @returns (`character(1)`, invisibly) The path to the configuration file. The
#'   config file is written as a side effect of this function. The rapid object
#'   is also written, and the path to that file (relative to `pkg_dir`) is saved
#'   in the config file.
#' @export
use_beekeeper <- function(
  x,
  api_abbr,
  ...,
  pkg_dir = ".",
  config_filename = "_beekeeper.yml",
  rapid_filename = "_beekeeper_rapid.rds"
) {
  rlang::check_dots_empty()
  .assert_is_pkg(pkg_dir)
  api_definition <- rapid::as_rapid(x)
  rapid_filename <- .write_rapid(api_definition, rapid_filename, pkg_dir)
  config_filename <- .write_config(
    api_definition,
    api_abbr,
    rapid_filename,
    config_filename,
    pkg_dir
  )

  return(invisible(fs::path(pkg_dir, config_filename)))
}

#' Write the rapid definition file
#'
#' @inheritParams .shared-params
#' @returns (`character(1)`) The written file path.
#' @keywords internal
.write_rapid <- function(api_definition, rapid_filename, pkg_dir) {
  rapid_filename <- stbl::stabilize_chr_scalar(rapid_filename)
  saveRDS(api_definition, fs::path(pkg_dir, rapid_filename))
  usethis::with_project(pkg_dir, usethis::use_build_ignore(rapid_filename))
  return(rapid_filename)
}

#' Write the beekeeper config file
#'
#' @inheritParams .shared-params
#' @returns (`character(1)`) The written config file path.
#' @keywords internal
.write_config <- function(
  api_definition,
  api_abbr,
  rapid_filename,
  config_filename,
  pkg_dir
) {
  config_filename <- stbl::stabilize_chr_scalar(config_filename)
  update_time <- strptime(Sys.time(), format = "%Y-%m-%d %H:%M:%S", tz = "UTC")
  yaml::write_yaml(
    list(
      api_title = api_definition@info@title,
      api_abbr = stbl::stabilize_chr_scalar(api_abbr),
      api_version = api_definition@info@version,
      rapid_filename = rapid_filename,
      updated_on = as.character(update_time)
    ),
    file = fs::path(pkg_dir, config_filename)
  )
  memoise::forget(read_config)
  usethis::with_project(pkg_dir, usethis::use_build_ignore(config_filename))
  return(config_filename)
}
